const masterTungPoints1010 = [
  {
    code: "1010.01",
    name: "Zheng Hui",
    pinyin: "Zhèng Huì",
    english: "Upright Meeting",
    location: "0.5 cun posterior to GV-20 Baihui.",
    needling: "Oblique, 0.1–0.3 cun.",
    reaction_area: "Brain.",
  },
  {
    code: "1010.02",
    name: "Zhou Yuan",
    pinyin: "Zhōu Yuán",
    english: "State Round",
    location: "1.3 cun lateral to 1010.01 Zheng Hui.",
    needling: "Oblique, 0.1–0.3 cun.",
    reaction_area: "Head-frontal region, Lung.",
  },
  {
    code: "1010.03",
    name: "Zhou Kun",
    pinyin: "Zhōu Kūn",
    english: "State Elder Brother",
    location: "1.3 cun lateral to 1010.02 Zhou Yuan.",
    needling: "Oblique, 0.1–0.3 cun.",
    reaction_area: "Head-lateral, Lung.",
  },
  {
    code: "1010.04",
    name: "Zhou Lun",
    pinyin: "Zhōu Lún",
    english: "State Mountain",
    location:
      "1.5 cun posterior to 1010.02 Zhou Yuan and 1.3 cun lateral to 1010.06 Hou Hui.",
    needling: "Oblique, 0.1–0.3 cun.",
    reaction_area: "Head-frontal region, Lung.",
  },
  {
    code: "1010.05",
    name: "Qian Hui",
    pinyin: "Qián Huì",
    english: "Anterior Meetings",
    location:
      "1.5 cun anterior to 1010.01 Zheng Hui, 0.5 cun posterior to GV-21 Qian Ding.",
    needling: "Oblique, 0.1–0.3 cun.",
    reaction_area: "Brain-assistant.",
  },
  {
    code: "1010.06",
    name: "Hou Hui",
    pinyin: "Hòu Huì",
    english: "Posterior Meeting",
    location:
      "1.5 cun posterior to 1010.01 Zheng Hui, 0.5 cun posterior to GV-19 Hou Ding.",
    needling: "Oblique, 0.1–0.3 cun.",
    reaction_area: "Brain, Spine.",
  },
  {
    code: "1010.07",
    name: "Zong Shu",
    pinyin: "Zǒng Shū",
    english: "Chief Pivot",
    location: "On the midline, 0.8 cun superior to back hairline.",
    needling: "Bloodletting.",
    reaction_area: "Dan Tian.",
  },
  {
    code: "1010.08",
    name: "Zhen Jing",
    pinyin: "Zhèn Jìng",
    english: "Calm Mind",
    location: "0.5 cun superior to the meeting of the two eyebrows.",
    needling:
      "Pinch the skin, transverse towards the bridge of the nose, 0.5–1 cun.",
    reaction_area: null,
  },
  {
    code: "1010.09",
    name: "Shang Li",
    pinyin: "Shàng Lǐ",
    english: "Upper Mile",
    location: "0.5 cun above the medial end of the eyebrow.",
    needling:
      "Transverse, towards the bridge of the nose, 0.5 cun. Bloodletting.",
    reaction_area: null,
  },
  {
    code: "1010.10",
    name: "Si Fu Er",
    pinyin: "Sì Fú Èr",
    english: "Four Bowels 2nd",
    location: "0.5 cun above the midpoint of the eyebrow.",
    needling: "Transverse, towards the eyebrow, 0.5 cun. Bloodletting.",
    reaction_area: null,
  },
  {
    code: "1010.11",
    name: "Si Fu Yi",
    pinyin: "Sì Fú Yī",
    english: "Four Bowels 1st",
    location: "0.5 cun above the lateral border of the eyebrow.",
    needling: "Transverse, towards the eyebrow, 0.5 cun. Bloodletting.",
    reaction_area: null,
  },
  {
    code: "1010.12",
    name: "Zheng Ben",
    pinyin: "Zhèng Běn",
    english: "Upright Root",
    location: "On the tip of the nose.",
    needling: "Perpendicular, 0.1–0.2 cun. Bloodletting.",
    reaction_area: null,
  },
  {
    code: "1010.13",
    name: "Ma Jin Shui",
    pinyin: "Mǎ Jīn Shuǐ",
    english: "Horse Metal Water",
    location:
      "On the lower border of the zygoma, in line with the outer canthus of the eye, 0.15 cun below Si-18 Quan Liao.",
    needling: "Perpendicular, 0.1–0.3 cun.",
    reaction_area: null,
  },
  {
    code: "1010.14",
    name: "Ma Kuai Shui",
    pinyin: "Mǎ Kuài Shuǐ",
    english: "Fast Horse Water",
    location: "0.4 cun inferior to 1010.13 Ma Jin Shui.",
    needling: "Perpendicular, 0.1–0.3 cun.",
    reaction_area: "Kidney, Urinary bladder.",
  },
  {
    code: "1010.15",
    name: "Fu Kuai",
    pinyin: "Fù Kuài",
    english: "Bowels Fast",
    location: "0.5 cun superior to Li-20 Ying Xiang.",
    needling:
      "Perpendicular, 0.1–0.3 cun. Threading from Li-20 Ying Xiang towards the bridge of the nose. Bloodletting.",
    reaction_area: null,
  },
  {
    code: "1010.16",
    name: "Liu Kuai",
    pinyin: "Liù Kuài",
    english: "Six Fast",
    location: "1.4 cun lateral to the middle of the philtrum groove.",
    needling: "Perpendicular, 0.1–0.3 cun.",
    reaction_area: null,
  },
  {
    code: "1010.17",
    name: "Qi Kuai",
    pinyin: "Qī Kuài",
    english: "Seven Fast",
    location: "0.5 cun lateral to the corner of the mouth.",
    needling: "Perpendicular, 0.1–0.3 cun. Bloodletting.",
    reaction_area: null,
  },
  {
    code: "1010.18",
    name: "Mu Zhi",
    pinyin: "Mù Zhī",
    english: "Wood Branch",
    location:
      "Two versions: (1) 1 cun lateral and 0.6 cun superior to 1010.13 Ma Jin Shui (Master Tung’s original), (2) 0.6 cun lateral to 1010.13 Ma Jin Shui (Hu Wen Zhi).",
    needling: "Perpendicular, 0.1–0.3 cun.",
    reaction_area: null,
  },
  [
    {
      code: "1010.24",
      name: "Zhou Jin",
      pinyin: "Zhōu Jīn",
      english: "Prefecture Metal",
      location: "1 cun posterior to 1010.23 Zhou Huo.",
      needling: "Perpendicular, 0.1–0.3 cun.",
      reaction_area: "Lung.",
    },
    {
      code: "1010.25",
      name: "Zhou Shui",
      pinyin: "Zhōu Shuǐ",
      english: "Prefecture Water",
      location: "1 cun posterior to 1010.23 Zhou Huo.",
      needling: "Perpendicular, 0.1–0.3 cun.",
      reaction_area: "Kidney.",
    },
  ],
];
