const masterTungPoints22 = [
  {
    code: "22.01",
    name: "Chong Zi",
    pinyin: "Chòng Zi",
    chinese: "大間穴",
    english: "Double Child",
    location:
      "On the thenar eminence, approximately 1 cun below the skin fold between the first and second metacarpal bones. Bring the thumb and second finger together; it lies at the intersection of a vertical line through the C line of the second finger and a transverse line at the proximal joint of the thumb. Opposite 22.04 Da Bai.",
    needling: "Perpendicular, 1–1.5 cun.",
    reaction_area: "Lung-sub-branch.",
    indications: [
      "Chest pain (pleurodynia)",
      "Lung cancer",
      "Emphysema",
      "Cough (with yellow phlegm)",
      "Asthma",
    ],
  },
  {
    code: "22.02",
    name: "Chong Xian",
    pinyin: "Chòng Xian",
    chinese: "重仙穴",
    english: "Double Immortal",
    location:
      "On the thenar eminence, at the junction of the first and second metacarpal bones. Opposite 22.05 Ling Gu on the palmar aspect.",
    needling: "Perpendicular, 1–1.5 cun.",
    reaction_area: "Lung-sub-branch, Heart-sub-branch.",
    indications: [
      "Dorsalgia (back pain)",
      "Fever",
      "Pneumonia",
      "Palpitations",
      "Knee pain",
      "Common cold",
      "Lung cancer",
      "Emphysema",
      "Bronchitis",
      "Cough (with yellow phlegm)",
      "Asthma",
    ],
  },
  {
    code: "22.03",
    name: "Shang Bai",
    pinyin: "Shàng Bái",
    chinese: "上白穴",
    english: "Upper White",
    location:
      "With the hand in a fist, on the dorsal aspect of the hand between the second and third metacarpal bones, 0.5 cun proximal to the metacarpophalangeal joint of the second and third fingers.",
    needling: "Perpendicular, 0.3–0.5 cun.",
    reaction_area:
      "Lung-sub-branch, Heart-sub-branch, Kidney (per Hu Wen Zhi).",
    indications: [
      "Gingivitis",
      "Sciatica",
      "Chest pain (pleurodynia)",
      "Keratitis",
      "Eye pain",
      "Blurred vision",
      "Astigmatism",
      "Eye itching",
      "Tearing when exposed to wind",
    ],
  },
  {
    code: "22.04",
    name: "Da Bai",
    pinyin: "Dà Bái",
    chinese: "大白穴",
    english: "Big White",
    location:
      "With the hand in a fist, 1 cun distal to 22.05 Ling Gu, adjacent to the second metacarpal bone, on the same horizontal line as LI-4 He Gu. Opposite 22.01 Chong Zi.",
    needling:
      "Perpendicular, 0.4–0.6 cun. Bloodletting in children for asthma, high fever, and acute pneumonia. Contraindicated during pregnancy.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "22.05",
    name: "Ling Gu",
    pinyin: "Líng Gǔ",
    chinese: "靈骨穴",
    english: "Spirit Bone",
    location:
      "With the hand in a fist, at the junction of the first and second metacarpal bones. Opposite 22.02 Chong Xian.",
    needling:
      "Perpendicular, 1–1.5 cun. Angle 1–2 cun toward 22.02 Chong Xian for lung, coldness, numbness of fingers, shoulder pain; or 2–3 cun toward 22.09 Wan Shun for back disorders. Contraindicated during pregnancy.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "22.06",
    name: "Zhong Bai",
    pinyin: "Zhōng Bái",
    chinese: "中白穴",
    english: "Middle White",
    location:
      "With the hand in a fist, on the dorsal aspect between the fourth and fifth metacarpal bones, 0.5 cun proximal to the metacarpophalangeal joint.",
    needling: "Perpendicular, 0.3–0.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "22.07",
    name: "Xia Bai",
    pinyin: "Xià Bái",
    chinese: "下白穴",
    english: "Lower White",
    location:
      "With the hand in a fist, on the dorsal aspect between the fourth and fifth metacarpal bones, 1 cun proximal to 22.06 Zhong Bai.",
    needling: "Perpendicular, 0.3–0.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "22.08–22.09",
    name: "Wan Shun",
    pinyin: "Wàn Shùn",
    chinese: "腕順穴",
    english: "Wrist Flow",
    location:
      "22.08 Wan Shun Yi: lateral aspect of the fifth metacarpal bone, 2.5 cun distal to the wrist, 0.5 cun proximal to SI-3 Hou Xi. 22.09 Wan Shun Er: lateral aspect of the fifth metacarpal bone, 1.5 cun distal to the wrist, 1 cun proximal to 22.08 Wan Shun Yi.",
    needling: "Perpendicular, 0.5–1 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "22.10",
    name: "Shou Jie",
    pinyin: "Shǒu Jiě",
    chinese: "手解穴",
    english: "Hand Release",
    location:
      "Two points. Shou Jie Yi: on the palm between the 4th and 5th metacarpal bones, where the tip of the little finger touches when flexed (same as Ht-8 Shao Fu). Shou Jie Er: 0.5 cun proximal to Shou Jie Yi.",
    needling: "Perpendicular, 0.3–0.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "22.11",
    name: "Tu Shui",
    pinyin: "Tǔ Shuǐ",
    chinese: "土水穴",
    english: "Earth Water",
    location:
      "Three points on the palmar aspect of the radial side of the first metacarpal bone. Divide the bone into four parts; the middle point aligns with Lu-10 Yu Ji.",
    needling: "Perpendicular, 0.5–1 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "Fen Bai",
    pinyin: "Fēn Bái",
    chinese: "分白穴",
    english: "Separate White",
    location:
      "Locate the point when the hand is in a fist. On the dorsal aspect of the hand, between the second and third metacarpal bones, 1 cun proximal to 22.03 Shang Bai.",
    needling: "Needle when the hand is in a fist. Perpendicular, 0.3–0.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "Gu Guan",
    pinyin: "Gǔ Guān",
    chinese: "骨關穴",
    english: "Bone Barrier",
    location:
      "On the base of the palm, in a depression about 0.5 cun distal to the prominence of the scaphoid bone.",
    needling: "Perpendicular, 0.3–0.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "Huai Ling",
    pinyin: "Huái Líng",
    chinese: "踝靈穴",
    english: "Effective Ankle",
    location:
      "Huái Líng [踝靈] is on the thumb at the radial side of the prominence of the head of the first metacarpophalangeal bone. Nèi Huái Líng [內踝靈] is on the ulnar side of the same prominence. Zhōng Huái Líng [中踝靈] is on the dorsal midline of the thumb between the other two points.",
    needling: "Perpendicular, 0.2–0.3 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "Jian Ning",
    pinyin: "Jiān Níng",
    chinese: "肩凝穴",
    english: "Stiff Shoulder",
    location: "On the radial side of the second metacarpophalangeal joint.",
    needling: "Perpendicular, 0.3–0.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "Jin Xing Shang / Xia",
    pinyin: "Jīn Xīng Shàng / Xià",
    chinese: "金星穴",
    english: "Venus (Upper & Lower)",
    location:
      "Jīn Xīng Shàng [金星上] – on the radial side of the second metacarpal bone, at the base of the bone head or end of the palm’s lifeline. Jīn Xīng Xià [金星下] – 0.3 cun anterior to Jīn Xīng Shàng.",
    needling: "Perpendicular, 0.3–0.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "Mu Guan",
    pinyin: "Mù Guān",
    chinese: "木關穴",
    english: "Wood Barrier",
    location:
      "At the base of the palm, about 0.5 cun distal to the prominence of the pisiform bone. Li Guo Zheng adds a point Zhong Guān between Gǔ Guān and Mù Guān.",
    needling: "Perpendicular, 0.3–0.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "Nei Bai",
    pinyin: "Nèi Bái",
    chinese: "內白穴",
    english: "Inner White",
    location:
      "On the dorsal aspect of the hand, between the fourth and fifth metacarpal bones, 0.5 cun proximal to the metacarpophalangeal joint; also described between the third and fourth metacarpals 0.5 cun proximal to the MCP joint when the hand is in a fist.",
    needling: "With the hand in a fist, perpendicular, 0.3–0.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "Shang / Xia Gao",
    pinyin: "Shàng / Xià Gāo",
    chinese: "上高穴 / 下高穴",
    english: "Upper and Lower Height",
    location:
      "Two points: Shàng Gāo is on the palm between metacarpal bones 4 and 5, 0.5 cun proximal to Shǒu Jiě Er (22.10); Xià Gāo is 1 cun proximal to Shàng Gāo.",
    needling: "Perpendicular, 0.3–0.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "San Cha San",
    pinyin: "Sān Chā Sān",
    chinese: "三叉三穴",
    english: "Three Intersections – Third",
    location:
      "On the dorsal aspect of the hand, between the fourth and fifth metacarpophalangeal joints. Locate with the hand in a fist.",
    needling: "Perpendicular, 0.3–0.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "San Cha Yi",
    pinyin: "Sān Chā Yī",
    chinese: "三叉一穴",
    english: "Three Intersections – First",
    location:
      "On the dorsal aspect of the hand, between the second and third metacarpophalangeal joints. Locate when the hand is in a fist.",
    needling:
      "Perpendicular threading technique 1–1.5 cun, thread between the second and third metacarpal bones.",
    reaction_area: "Lung sub-branch; Kidney assistant.",
    indications: null,
  },
  {
    code: null,
    name: "San Cha Er",
    pinyin: "Sān Chā Èr",
    chinese: "三叉二穴",
    english: "Three Intersections - Second",
    location:
      "On the dorsal aspect of the hand, between the 3rd and 4th metacarpophalangeal joints. The point should be located when the hand is in a fist.",
    needling:
      "Perpendicular threading technique, 1–1.5 cun. Thread the needle between the 2nd and 3rd metacarpal bones.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "San Feng",
    pinyin: "Sān Fēng",
    chinese: "三風穴",
    english: "Three Winds",
    location:
      "Three points are located on the palmar aspect of the hand, between the 1st and 2nd metacarpal bones. The first point is 0.25 cun proximal to the junction of the two fingers; the second is 0.25 cun proximal to the first point, and the third is 0.25 cun proximal to the second point.",
    needling: "Perpendicular, 0.2–0.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "San Huo",
    pinyin: "Sān Huǒ",
    chinese: "三火穴",
    english: "Three Fire",
    location:
      "Three points are located on the palmar aspect of the hand, on the 3rd metacarpal bone. The middle point is in the middle of the bone; the distal point is 0.5 cun distal to the middle, and the proximal point is 0.5 cun proximal to the middle point.",
    needling: "Oblique, 0.2–0.3 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "San He",
    pinyin: "Sān Hé",
    chinese: "三河穴",
    english: "Three Rivers",
    location:
      "Three points are located on the palmar aspect of the hand, between the 4th and 5th metacarpal bones. The first point is 0.25 cun proximal to the junction of the two fingers; the second is 0.25 cun proximal to the first point, and the third is 0.25 cun proximal to the second point.",
    needling: "Perpendicular, 0.2–0.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "San Hai",
    pinyin: "Sān Hǎi",
    chinese: "三海穴",
    english: "Three Seas",
    location:
      "Three points are located on the palmar aspect of the hand, on the 5th metacarpal bone. The middle point is in the middle of the bone; the distal point is 0.5 cun distal to the middle, and the proximal point is 0.5 cun proximal to the middle point.",
    needling: "Oblique, 0.2–0.3 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "San Jian",
    pinyin: "Sān Jiān",
    chinese: "三肩穴",
    english: "Three Shoulder Points",
    location:
      "Three points are located on the ulnar border of the dorsal aspect of the first metacarpal bone's first segment. Two points are near the head of the bone, and the third is between them.",
    needling:
      "Needle when the hand is in a fist. Perpendicular, 0.5–1 cun. For shoulder disorders, needle on the affected side.",
    reaction_area: "Lung sub-branch; Kidney.",
    indications: null,
  },
  {
    code: null,
    name: "San Mao",
    pinyin: "Sān Máo",
    chinese: "三毛穴",
    english: "Three Hair (Second Metacarpal)",
    location:
      "Three points are located on the palmar aspect of the hand, on the 2nd metacarpal bone. The middle point is in the middle of the bone; the distal point is 0.5 cun distal to the middle, and the proximal point is 0.5 cun proximal to the middle point.",
    needling: "Oblique, 0.2–0.3 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "San Xing",
    pinyin: "Sān Xīng",
    chinese: "三星穴",
    english: "Three Stars",
    location:
      "Three points are located on the palmar aspect of the hand, on the 4th metacarpal bone. The middle point is in the middle of the bone; the distal point is 0.5 cun distal to the middle, and the proximal point is 0.5 cun proximal to the middle point.",
    needling: "Oblique, 0.2–0.3 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "Wai Bai",
    pinyin: "Wài Bái",
    chinese: "外白穴",
    english: "Outer White",
    location:
      "On the dorsal aspect of the hand, between the 3rd and 4th metacarpal bones, 1 cun proximal to Nèi Bái. To locate, make a fist.",
    needling: "With the hand in a fist, perpendicular, 0.3–0.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "Zhong Kui",
    pinyin: "Zhòng Kuí",
    chinese: "重魁穴",
    english: "Heavy Head",
    location:
      "On the radial side of the index finger, proximal to the head of the 2nd metacarpal bone, between the tendon and the head of the bone, close to LI-3 San Jian. Alternate: Young Wei Chieh places 22.04 Da Bai here.",
    needling:
      "Needle when the hand is in a fist. Perpendicular, 0.5–1 cun. Bloodletting in children. Caution: contraindicated during pregnancy.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "Zhi Han",
    pinyin: "Zhǐ Hàn",
    chinese: "止汗穴",
    english: "Stop Sweating",
    location:
      "On the dorsal aspect of the hand, between the third and fourth metacarpal bones, 0.5 cun proximal to Nèi Bái. To find the point, make a fist with the hand.",
    needling: "With the hand in a fist, perpendicular, 0.3–0.5 cun.",
    reaction_area: null,
    indications: null,
  },
];
