const masterTungPoints44 = [
  {
    code: "44.01",
    name: "San Jin",
    pinyin: "Sān Jīn",
    chinese: "三金",
    english: "Three Metals",
    location:
      "On the anterior aspect of the humerus, 1.5 cun proximal to Lu-5 Che Ze. Nei Jin: 0.5 cun proximal to 44.01 Fen Jin. He Jin: 0.5 cun distal to 44.01 Fen Jin.",
    needling: "Perpendicular, 0.5–1 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "44.02",
    name: "Hou Zhui",
    pinyin: "Hòu Zhuī",
    chinese: "後椎",
    english: "Back Vertebra",
    location:
      "On the posterior aspect of the humerus, on the lateral border, 2.5 cun proximal to the elbow crease.",
    needling: null,
    reaction_area: null,
    indications: null,
  },
  {
    code: "44.03",
    name: "Shou Ying",
    pinyin: "Shǒu Yīng",
    chinese: "首英",
    english: "Head Wisdom",
    location:
      "On the posterior aspect of the humerus, on the lateral border, 4.5 cun proximal to the elbow crease or 2 cun superior to 44.02 Hou Zhui. The distance from the axillary fold to the cubital crease is 9 cun; 4.5 cun is half that distance.",
    needling: "Perpendicular, 0.3–0.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "44.04",
    name: "Fu Ding",
    pinyin: "Fù Dǐng",
    chinese: "富頂",
    english: "Wealth Top",
    location:
      "On the posterior aspect of the humerus at the lateral border, 7 cun proximal to the elbow crease or 1 cun superior to Yu Ying (44).",
    needling: null,
    reaction_area: null,
    indications: null,
  },
  {
    code: "44.05",
    name: "Hou Zhi",
    pinyin: "Hòu Zhī",
    chinese: "後枝",
    english: "Back Branch",
    location:
      "On the lateral border's posterior aspect of the humerus, 8 cun proximal to the elbow crease, or 1 cun superior to 44.04 Fu Ding.",
    needling: null,
    reaction_area: null,
    indications: null,
  },
  {
    code: "44.06",
    name: "Jian Zhong",
    pinyin: "Jiān Zhōng",
    chinese: "肩中穴",
    english: "Shoulder Center",
    location:
      "In the middle of the deltoid muscle, 2.5 cun inferior to the acromion.",
    needling: "Perpendicular, 0.5–1 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "44.07",
    name: "Bei Mian",
    pinyin: "Bèi Miàn",
    chinese: "背面穴",
    english: "Back Face",
    location:
      "0.3 cun superior to Jian Feng (44). The point is found in the hollow formed when the arm is raised vertically, above the shoulder joint.",
    needling:
      "Perpendicular, 0.3–0.5 cun. Bloodletting treats general weakness, painful legs, dry cholera, and intestinal cholera.",
    reaction_area: "Cinnabar field nerve [丹田神經].",
    indications: ["Swollen abdomen", "Weak voice"],
  },
  {
    code: "44.08",
    name: "Ren Zong",
    pinyin: "Rén Zōng",
    chinese: "人宗穴",
    english: "Human Ancestor",
    location:
      "3 cun distal to the crease of the elbow, medial to the biceps brachii muscle, between the humerus and the biceps brachii muscle.",
    needling: null,
    reaction_area: null,
    indications: null,
  },
  {
    code: "44.09",
    name: "Di Zong",
    pinyin: "Dì Zōng",
    chinese: "地宗穴",
    english: "Earth Ancestor",
    location:
      "3 cun superior to 44.08 Ren Zong, between the humerus and the biceps brachii muscle.",
    needling: "Perpendicular, 1–2 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "44.10",
    name: "Tian Zong",
    pinyin: "Tiān Zōng",
    chinese: "天宗穴",
    english: "Heavenly Ancestor",
    location:
      "3 cun superior to 44.09 Di Zong, between the humerus and the biceps brachii muscle.",
    needling: "Perpendicular, 1–1.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "44.11",
    name: "Yun Bai",
    pinyin: "Yún Bái",
    chinese: "雲白穴",
    english: "White Cloud",
    location:
      "2 cun medially to 44.06 Jian Zhong at the medial border of the deltoid muscle. Shang Yun Bai [上雲白] is 2 cun superior to 44.11 Yun Bai.",
    needling: "Perpendicular, 0.3–0.5 cun.",
    reaction_area: "Lung-assistant, Six-Fu.",
    indications: null,
  },
  {
    code: "44.12",
    name: "Li Bai",
    pinyin: "Lǐ Bái",
    chinese: "李白穴",
    english: "White Plum",
    location:
      "2 cun inferior to 44.11 Yun Bai at the medial border of the deltoid muscle.",
    needling: "Perpendicular, 0.3–0.5 cun.",
    reaction_area: "Kidney-assistant, Lung-branch.",
    indications: null,
  },
  {
    code: "44.13",
    name: "Zhi Tong",
    pinyin: "Zhī Tōng",
    chinese: "支通穴",
    english: "Branch Connect",
    location:
      "On the posterior aspect of the arm, at the medial border of the humerus, 4.5 cun proximal to the elbow crease. The point is located 1 cun posterior to 44.03 Shou Ying.",
    needling: "Perpendicular, 0.6–1 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "44.14",
    name: "Luo Tong",
    pinyin: "Luò Tōng",
    chinese: "落通穴",
    english: "Lower Connect",
    location:
      "On the posterior aspect of the arm, 1 cun posterior to 44.04 Fu Ding, at the medial border of the humerus.",
    needling: "Perpendicular, 0.3–0.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "44.15",
    name: "Xia Qu",
    pinyin: "Xià Qū",
    chinese: "下曲穴",
    english: "Lower Curve",
    location:
      "2 cun inferior to 44.16 Shang Qu at the lateral border of the deltoid muscle. Shang Qu Shang [上曲上] is 2 cun superior to 44.16 Shang Qu.",
    needling: "Perpendicular, 0.3–0.5 cun.",
    reaction_area: "Lung, Liver-branch.",
    indications: null,
  },
  {
    code: null,
    name: "Yu Ying",
    pinyin: "Yù Yīng",
    chinese: "育英穴",
    english: "Grow Flower",
    location:
      "On the posterior aspect of the humerus on the lateral border, 6 cun proximal to the elbow crease or 1.5 cun superior to 44.03 Shou Ying.",
    needling: null,
    reaction_area: null,
    indications: null,
  },
];
