const masterTungPoints77 = [
  {
    code: "77.01",
    name: "Zheng Jin",
    pinyin: "Zhèng Jīn",
    chinese: "正筋穴",
    translation: "Upright Tendon",
    location:
      "At the center of the Achilles tendon, 3.5 cun superior to the base of the heel, between Ki-3 Tai Xi and Bl-60 Kun Lun.",
    needling:
      "Perpendicular, through the tendon, 0.5–0.8 cun. Ensure the needle is centered in the tendon before insertion.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.02",
    name: "Zheng Zong",
    pinyin: "Zhèng Zōng",
    chinese: "正宗穴",
    translation: "Upright Ancestor",
    location:
      "At the center of the Achilles tendon, 2 cun proximally to 77.01 Zheng Jin.",
    needling:
      "Perpendicular, through the tendon, 0.5–0.8 cun. Ensure needle is at the tendon center. Strong individuals should be needled seated; weak individuals lying down.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.03",
    name: "Zheng Shi",
    pinyin: "Zhèng Shì",
    chinese: "正士穴",
    translation: "Upright Scholar",
    location:
      "At the center of the Achilles tendon, 2 cun proximally to 77.02 Zheng Zong.",
    needling:
      "Perpendicular, through the tendon, 0.5–1 cun. Ensure the needle is centered. If pain is one-sided, needle the affected side; if central, needle bilaterally.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.04",
    name: "Bo Qiu",
    pinyin: "Bó Qiú",
    chinese: "搏球穴",
    translation: "Catching Ball",
    location: "2.5 cun proximally to 77.03 Zheng Shi.",
    needling:
      "Perpendicular, 1–2 cun. Needling to the bone yields better results. For chronic or stubborn diseases, bloodletting at the point area is recommended.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.05–07",
    name: "San Zhong",
    pinyin: "Sān Zhòng",
    chinese: "三重穴",
    translation: "Three Weights",
    location:
      "77.05 Yi Zhong [一重]: 3 cun superior to the lateral malleolus and 1 cun anterior to the fibula. 77.06 Er Zhong [二重]: 2 cun superior to 77.05 Yi Zhong. 77.07 San Zhong [三重]: 2 cun superior to 77.06 Er Zhong.",
    needling:
      "Perpendicular, 1–2 cun. Bloodletting in the case of Luo channels in the area of the points.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.08",
    name: "Si Hua Shang",
    pinyin: "Sì Huā Shàng",
    chinese: "四花上穴",
    translation: "Four Flowers Upper",
    location:
      "3 cun inferior to St-35 Du Bi, between the tibia and the Tibialis Anterior muscle, at the same level as St-36 Zu San Li.",
    needling:
      "Perpendicular insertion, 2–3 cun. 2 cun for asthma; 3 cun for heart diseases; 3 cun for cholera with leg cramps (to be used with 77.04 Bo Qiu). Bloodletting in the connecting channels improves treatment for heart disease, asthma, gastric diseases, ulcers, and acute gastric pain. Needle on the painful side for shoulder, elbow, and finger pain.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.09",
    name: "Si Hua Zhong",
    pinyin: "Sì Huā Zhōng",
    chinese: "四花中穴",
    translation: "Four Flowers Middle",
    location:
      "4.5 cun inferior to 77.08 Si Hua Shang, between the tibia and the Tibialis Anterior muscle. The point is midway between St-37 Shang Ju Xu and St-39 Xia Ju Xu.",
    needling: "Perpendicular insertion, 1–2 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.10",
    name: "Si Hua Fu",
    pinyin: "Sì Huā Fù",
    chinese: "四花副穴",
    translation: "Four Flowers Deputy",
    location:
      "2.5 cun inferior to 77.09 Si Hua Zhong, between the tibia and the Tibialis Anterior muscle. Located 1 cun distal to St-39 Xia Ju Xu.",
    needling: "Perpendicular insertion, 1–2 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.11",
    name: "Si Hua Xia",
    pinyin: "Sì Huā Xià",
    chinese: "四花下穴",
    translation: "Four Flowers Lower",
    location:
      "5 cun inferior to 77.09 Si Hua Zhong, or 2.5 cun inferior to 77.10 Si Hua Fu, between the tibia and the Tibialis Anterior muscle.",
    needling: "Perpendicular insertion, 1.5–2.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.12",
    name: "Fu Chang",
    pinyin: "Fù Cháng",
    chinese: "腑腸穴",
    translation: "Bowel Intestine",
    location: "1.5 cun superior to 77.11 Si Hua Xia.",
    needling: "Perpendicular insertion, 1.5–2 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.13",
    name: "Si Hua Li",
    pinyin: "Sì Huā Lǐ",
    chinese: "四花裏穴",
    translation: "Four Flowers Medial",
    location:
      "1.2 cun medial to 77.09 Si Hua Zhong at the inner border of the tibia. Recommended to locate point by inner tibial border rather than measuring cun.",
    needling: "Perpendicular insertion, 1.5–2 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.14",
    name: "Si Hua Wai",
    pinyin: "Sì Huā Wài",
    chinese: "四花外穴",
    translation: "Four Flowers Lateral",
    location: "1.5 cun lateral to 77.09 Si Hua Zhong.",
    needling: "Perpendicular insertion, 1.5–2 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.15",
    name: "Shang Chun",
    pinyin: "Shàng Chún",
    chinese: "上唇穴",
    translation: "Upper Lip",
    location:
      "At the lower border of the patella, in the middle of the patellar tendon.",
    needling:
      "Bloodletting of the tendon. If black blood is drawn, results improve. Perpendicular insertion 0.2–0.5 cun treats mouth angle deviation and elbow pain.",
    reaction_area: "Extra points outside channels, Lips.",
    indications: null,
  },
  {
    code: "77.16",
    name: "Xia Chun",
    pinyin: "Xià Chún",
    chinese: "下唇穴",
    translation: "Lower Lip",
    location: "1 cun inferior to 77.15 Shang Chun.",
    needling:
      "Bloodletting of the tendon. If black blood is drawn, results improve. Perpendicular insertion 0.2–0.5 cun used for mouth angle deviation and elbow pain.",
    reaction_area: "Extra points outside channels, Lips.",
    indications: null,
  },
  {
    code: "77.17",
    name: "Tian Huang",
    pinyin: "Tiān Huáng",
    chinese: "天皇穴",
    translation: "Heavenly Emperor",
    location:
      "1 cun inferior to the medial condyle of the tibia, and 1 cun inferior to Sp-9 Yin Ling Quan.",
    needling:
      "Perpendicular insertion, 0.5–1 cun. Warning: Should not be needled during pregnancy.",
    reaction_area: "Kidney, Six-Fu, Heart-sub-branch.",
    indications: null,
  },
  {
    code: "77.18",
    name: "Shen Guan",
    pinyin: "Shèn Guān",
    chinese: "腎關穴",
    translation: "Kidney Gate",
    location: "1.5 cun inferior to 77.17 Tian Huang.",
    needling:
      "Perpendicular, 1–2 cun. For treating kidney deficiency — 2 cun. Lai Jing Xiong: Perpendicular to treat pain and stiffness in the chest and to strengthen the heart; Transversely to treat kidney deficiency, pain above the eye bones, and frontal headache.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.19",
    name: "Di Huang",
    pinyin: "Dì Huáng",
    chinese: "地皇穴",
    translation: "Earth Emperor",
    location: "4 cun proximal to 77.21 Ren Huang.",
    needling: "Perpendicular, 1–2 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.20",
    name: "Si Zhi",
    pinyin: "Sì Zhī",
    chinese: "四肢穴",
    translation: "Four Limbs",
    location:
      "On the medial aspect of the tibia, 4.5 cun superior to the medial malleolus.",
    needling:
      "Obliquely (30°) towards the knee, 0.6–1.2 cun to treat limb disorders. Perpendicular, 0.6–1.2 cun to treat neck pain. Warning: This point should not be needled during pregnancy.",
    reaction_area: "Heart-branch, Kidney-sub-branch, and the four limbs.",
    indications: null,
  },
  {
    code: "77.21",
    name: "Ren Huang",
    pinyin: "Rén Huáng",
    chinese: "人皇穴",
    translation: "Human Emperor",
    location: "3.5 cun superior to the apex of the medial malleolus.",
    needling: "Perpendicular, 0.6–1.2 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.22",
    name: "Ce San Li",
    pinyin: "Cè Sān Lǐ",
    chinese: "側三里穴",
    translation: "Beside 3 Miles",
    location:
      "1.5 cun lateral to 77.08 Si Hua Shang and 0.5 cun lateral to St-36 Zu San Li. Locate the point on the lateral border of the tibialis anterior.",
    needling: "Perpendicular, 0.5–1 cun. Needle on the healthy side.",
    reaction_area: "Lung-sub-branch, Teeth.",
    indications: null,
  },
  {
    code: "77.23",
    name: "Ce Xia San Li",
    pinyin: "Cè Xià Sān Lǐ",
    chinese: "側下三里穴",
    translation: "Beside 3 Miles Lower",
    location: "2 cun inferior to 77.22 Ce San Li.",
    needling: "Perpendicular, 0.5–1 cun. Needle on the healthy side.",
    reaction_area: "Lung-sub-branch, Teeth.",
    indications: null,
  },
  {
    code: "77.24",
    name: "Zu Qian Jin",
    pinyin: "Zú Qiān Jīn",
    chinese: "足千金穴",
    translation: "Leg Thousand Metal",
    location:
      "0.5 cun laterally (posterior) and 2 cun inferior to 77.23 Ce Xia San Li.",
    needling:
      "Perpendicular, 0.5–1 cun. Bloodletting. Bilateral needling for disorders of the throat and thyroid gland. For other disorders, needle on the opposite side.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.25",
    name: "Zu Wu Jin",
    pinyin: "Zú Wǔ Jīn",
    chinese: "足五金穴",
    translation: "Leg Five Metal",
    location: "2 cun inferior to 77.24 Zu Qian Jin.",
    needling:
      "Perpendicular, 0.5–1 cun. Bloodletting. Bilateral needling for disorders of the throat and thyroid gland. For other disorders, needle on the opposite side.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.26",
    name: "Qi Hu",
    pinyin: "Qì Hǔ",
    chinese: "七虎穴",
    translation: "Seven Tigers",
    location:
      "Three points. The first point is located 1.5 cun proximally to Bl-60 Kun Lun. The second point is located 2 cun proximally to the first point. The third point is located 2 cun proximally to the second point.",
    needling: "Perpendicular, 0.5–0.8 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.27",
    name: "Wai San Guan",
    pinyin: "Wài Sān Guān",
    chinese: "外三關穴",
    translation: "Exterior Three Gates",
    location:
      "Three points. On the line connecting the head of the fibula to the head of the lateral malleolus on the fibula bone. The middle point is located at the midpoint of this line. The upper point is midway between the fibular head and the midpoint. The lower point is midway between the lateral malleolus and the midpoint. All three points are on the fibula, with the middle point close to 77.25 Zu Wu Jin.",
    needling: "Perpendicular, 1–1.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "77.28",
    name: "Guang Ming",
    pinyin: "Guāng Míng",
    chinese: "光明穴",
    english: "Bright Light",
    location: "Between KI-3 Tai Xi and KI-7 Fu Liu, adjacent to the tibia.",
    needling: "Perpendicular, 0.5–1 cun.",
    reaction_area:
      "Master Tung does not indicate an action area. Hu Wen Zi: eyes.",
  },
  {
    code: null,
    name: "Liu Shui",
    pinyin: "Liù Shuǐ",
    chinese: "六水穴",
    english: "Six Water",
    location:
      "Six points: Shui Zhi is 2 cun lateral to the tip of the medial malleolus and 6 cun proximally; Shui Ming 1 cun above Shui Zhi; Shui Qing 1 cun above Shui Ming; Shui Zhen 1 cun above Shui Qing; Shui Yin 1 cun above Shui Zhen; Shui Quan 1 cun above Shui Yin.",
    needling: "Perpendicular, 0.5–1 cun.",
    reaction_area: "Water metabolism, urination, edema.",
  },
  {
    code: null,
    name: "Shuang Long",
    pinyin: "Shuāng Lóng",
    chinese: "雙龍穴",
    english: "Double Dragon",
    location:
      "Two points: Shuang Long Yi is located 1.5 cun below the knee eye (ST-35 Du Bi) in the depression on the lateral side of the tibia. Shuang Long Er is located 0.6 cun distally to Shuang Long Yi.",
    needling: "Perpendicular, 0.5–0.8 cun.",
    reaction_area: "Lung-branch.",
  },
  {
    code: null,
    name: "Shang Yu Xia Yu",
    pinyin: "Shàng Yú Xià Yú",
    chinese: "上俞下俞穴",
    english: "Upper/Lower Transport",
    location:
      "Shang Yu: located in the popliteal crease, 0.5 cun lateral to BL-40 Wei Zhong. Xia Yu: located in the popliteal crease, 0.5 cun medial to BL-40 Wei Zhong.",
    needling: "Bloodletting.",
    reaction_area: null,
  },
  {
    code: "SP-9",
    name: "Yin Ling Quan",
    pinyin: "Yīn Líng Quán",
    chinese: "陰陵泉穴",
    english: "Yin Mound Spring",
    location:
      "On the medial side of the lower leg, in a depression in the angle formed by the medial condyle of the tibia and the posterior border of the tibia.",
    needling: "Perpendicular, 1–1.5 cun.",
    reaction_area: "Kidney.",
  },
  {
    code: null,
    name: "Zheng Nao",
    pinyin: "Zhèng Nǎo",
    chinese: "正腦穴",
    english: "Rectifying Brain",
    location:
      "Zheng Nao Yi: in the center of the Achilles tendon, 4.5 cun superior to the bottom of the heel. Zheng Nao Er: 2 cun above Zheng Nao Yi. Zheng Nao San: 2 cun above Zheng Nao Er.",
    needling: "Perpendicular, 0.5–1 cun.",
    reaction_area: null,
  },
  {
    code: null,
    name: "Zheng Yang",
    pinyin: "Zhèng Yáng",
    chinese: "正陽穴",
    english: "Rectifying Yang",
    location:
      "Zheng Yang Yi: 1 cun inferior to BL-40 Wei Zhong. Zheng Yang Er: 1 cun lateral to Zheng Yang Yi. Zheng Yang San: 1 cun medial to Zheng Yang Yi.",
    needling: "Perpendicular, 0.5–1 cun.",
    reaction_area: null,
  },
];
