const masterTungPoints66 = [
  {
    code: "66.05",
    name: "Men Jin",
    pinyin: "Mén Jīn",
    chinese: "門金穴",
    english: "Metal Gate",
    location:
      "In the anterior depression at the junction of the second and third metatarsal bones. It is proximal to St-43 Xian Gu, on the same transverse plane as 66.04 Huo Zhu, and opposite Kid-1 Yong Quan.",
    needling: "Perpendicular, 1–1.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "66.06",
    name: "Mu Liu",
    pinyin: "Mù Liú",
    chinese: "木留穴",
    english: "Wood Remain",
    location:
      "On the dorsal aspect of the foot, in a depression at the junction of the third and fourth metatarsal bones.",
    needling: "Perpendicular, 1–1.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "66.07",
    name: "Mu Dou",
    pinyin: "Mù Dòu",
    chinese: "木斗穴",
    english: "Wood Dipper",
    location:
      "On the dorsal aspect of the foot between the third and fourth metatarsal bones, 0.5 cun from the metatarsophalangeal joint.",
    needling: "Perpendicular, 1–1.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "66.08",
    name: "Liu Wan",
    pinyin: "Liù Wán",
    chinese: "六完穴",
    english: "Sixth Finish",
    location:
      "On the dorsal aspect of the foot between the fourth and fifth metatarsal bones, 0.5 cun distal to the metatarsophalangeal joint. The point is opposite 55.05 Hua Gu Si (66).",
    needling: "Perpendicular, 1–1.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "66.09",
    name: "Shui Qu",
    pinyin: "Shuǐ Qū",
    chinese: "水曲穴",
    english: "Water Bend",
    location:
      "On the dorsal aspect of the foot in a depression at the junction of the fourth and fifth metatarsal bones, 1 cun proximal to 66.08 Liu Wan.",
    needling: "Perpendicular, 1–1.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: "66.10",
    name: "Huo Lian",
    pinyin: "Huǒ Lián",
    chinese: "火連穴",
    english: "Fire Connection",
    location:
      "On the medial side of the first metatarsal bone, in a depression 2 cun posterior to the first metatarsophalangeal joint.",
    needling:
      "Perpendicular, 0.5–0.8 cun. Caution: Do not needle bilaterally. Contraindicated during pregnancy.",
    reaction_area: "Heart-sub-branch, Kidney-assistant.",
    indications: null,
  },
  {
    code: "66.11",
    name: "Huo Ju",
    pinyin: "Huǒ Jú",
    chinese: "火菊穴",
    english: "Fire Chrysanthemum",
    location:
      "On the medial side of the first metatarsal bone at the joint between the head of the first metatarsal bone and the medial cuneiforms, proximal to Sp-4 Gong Sun.",
    needling:
      "Perpendicular, 0.5–1 cun. Caution: Do not needle bilaterally. Contraindicated during pregnancy.",
    reaction_area: "Heart-sub-branch, Kidney-assistant.",
    indications: null,
  },
  {
    code: "66.12",
    name: "Huo San",
    pinyin: "Huǒ Sàn",
    chinese: "火散穴",
    english: "Fire Scatter",
    location:
      "1 cun posterior to 66.11 Huo Ju. The point is located proximally to Kid-2 Ran Gu.",
    needling:
      "Perpendicular, 0.5–0.8 cun. Caution: Do not needle bilaterally. Contraindicated during pregnancy.",
    reaction_area: "Heart-sub-branch, Kidney, Six-Fu-assistant.",
    indications: null,
  },
  {
    code: "66.13",
    name: "Shui Jing",
    pinyin: "Shuǐ Jīng",
    chinese: "水晶穴",
    english: "Water Crystal",
    location: "2 cun inferior to the apex of the medial malleolus.",
    needling: "Perpendicular, 0.5–1 cun.",
    reaction_area: "Uterus.",
    indications: null,
  },
  {
    code: "66.14",
    name: "Shui Xiang",
    pinyin: "Shuǐ Xiàng",
    chinese: "水相穴",
    english: "Water Minister",
    location:
      "Posterior to the medial malleolus, in the depression at the anterior border of the Achilles tendon. It is at the same level as Kid-3 Tai Xi but adjacent to the Achilles tendon.",
    needling: "Perpendicular, 0.3–0.5 cun.",
    reaction_area: "Kidney-branch, Brain.",
    indications: null,
  },
  {
    code: "66.15",
    name: "Shui Xian",
    pinyin: "Shuǐ Xiān",
    chinese: "水仙穴",
    english: "Water Immortal",
    location: "2 cun inferior to 66.14 Shui Xiang on the calcaneus bone.",
    needling: "Oblique 0.3–0.5 cun.",
    reaction_area: "Kidney-branch, Brain.",
    indications: null,
  },
  {
    code: null,
    name: "Liu Xi",
    pinyin: "Liù Xī",
    chinese: "六溪穴",
    english: "Six Ravines",
    location:
      "Shang Xi [上溪]: 1 cun distal to St-41 Jie Xi. Xia Xi [下溪]: 1 cun distal to Shang Xi. Wai Xi [外溪]: 1 cun lateral to Shang Xi. Qian Xi [前溪]: 1 cun distal to Wai Xi. Nei Xi [內溪]: 1 cun medial to Shang Xi. Shui Xi [水溪]: 1 cun distal to Nei Xi.",
    needling: null,
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "Men Jin Xia",
    pinyin: "Mén Jīn Xià",
    chinese: "門金下穴",
    english: "Lower Metal Gate",
    location:
      "Between the second and third metatarsal bones, 0.5 cun from the metatarsophalangeal joint, and 0.5 cun proximally to ST-44 Nei Ting.",
    needling: "Perpendicular, 1–1.5 cun.",
    reaction_area: null,
    indications: null,
  },
  {
    code: null,
    name: "San Shui",
    pinyin: "Sān Shuǐ",
    chinese: "三水穴",
    english: "Three Waters",
    location:
      "Three points are located inferior to the medial malleolus. Shui Fen [水分]: 1 cun inferior to Ki-6 Zhao Hai. Shui Men [水門]: 0.5 cun posterior to Shui Fen. Shui Xiang [水香]: 0.5 cun anterior to Shui Fen.",
    needling: "Oblique, 0.5–1 cun. Bloodletting.",
    reaction_area: "Kidney.",
    indications: null,
  },
  {
    code: null,
    name: "Wan Tong",
    pinyin: "Wàn Tōng",
    chinese: "腕通穴",
    english: "Wrist Pain",
    location:
      "The first point is located under the calcaneus, beneath the tip of the lateral malleolus. The second point is located 2 cun distal to the first point.",
    needling: "Perpendicular, 0.5–1 cun.",
    reaction_area: null,
    indications: ["Wrist pain"],
  },
];
