const acupunctureLocations = {
  RN1: "Between the anus and the root of the scrotum in males and between the anus and posterior labial commissure in females",
  RN2: "On the midpoint of the upper border of the symphysis pBLis",
  RN3: "On the midline of the abdomen, 4cun below the umbilicus",
  RN4: "On the midline of the abdomen, 3cun below the umbilicus",
  RN5: "On the midline of the abdomen, 2cun below the umbilicus",
  RN6: "On the midline of the abdomen, 1.5cun below the umbilicus",
  RN7: "On the midline of the abdomen, 1cun below the umbilicus",
  RN8: "In the center of the umbilicus",
  RN9: "On the midline of the abdomen, 1cun above the umbilicus",
  RN10: "On the midline of the abdomen, 2cun above the umbilicus",
  RN11: "On the midline of the abdomen, 3cun above the umbilicus",
  RN12: "On the midline of the abdomen, 4cun above the umbilicus",
  RN13: "On the midline of the abdomen, 5cun above the umbilicus",
  RN14: "On the midline of the abdomen, 6cun above the umbilicus",
  RN15: "Below the xiphoid process, 7cun above the umbilicus",
  RN16: "On the midline of the sternum, level with the 5th intercostal space",
  RN17: "On the anterior midline, level with the 4th intercostal space, midway between the nipples",
  RN18: "On the anterior midline, at the level with the 3rd intercostal space, midway between the nipples",
  RN19: "On the anterior midline, at the level with the 2nd intercostal space, midway between the nipples",
  RN20: "On the anterior midline, at the level with the 1st intercostal space",
  RN21: "On the anterior midline, in the center of the sternal manBLrium, 1cun below RN22",
  RN22: "In the center of the suprasternal fossa",
  RN23: "Above the Adam’s apple, in the depression above the upper border of the hyoid bone",
  RN24: "In the depression in the center of the mentolabial groove",

  DU1: "Midway between the tip of the coccyx and the anus",
  DU2: "In the hiatus of the sacrum",
  DU3: "Below the spinous process of the 4th lumbar vertebra",
  DU4: "Below the spinous process of the 2nd lumbar vertebra",
  DU5: "Below the spinous process of the 1st lumbar vertebra",
  DU6: "Below the spinous process of the 11th thoracic vertebra",
  DU7: "Below the spinous process of the 10th thoracic vertebra",
  DU8: "Below the spinous process of the 9th thoracic vertebra",
  DU9: "Below the spinous process of the 7th thoracic vertebra",
  DU10: "Below the spinous process of the 6th thoracic vertebra",
  DU11: "Below the spinous process of the 5th thoracic vertebra",
  DU12: "Below the spinous process of the 3rd thoracic vertebra",
  DU13: "Below the spinous process of the 1st thoracic vertebra",
  DU14: "Below the spinous process of the 7th cervical vertebra",
  DU15: "0.5cun above midpoint of posterior hairline",
  DU16: "1cun above midpoint of posterior hairline, below external occipital protBLerance",
  DU17: "On the midline of the head, 1.5cun directly above DU16",
  DU18: "On the midline of the head, 1.5cun directly above DU17",
  DU19: "On the midline of the head, 1.5cun directly above DU18",
  DU20: "On the midline of the head, 7cun above posterior hairline",
  DU21: "On the midline of the head, 1.5cun anterior to DU20",
  DU22: "2cun posterior to midpoint of anterior hairline",
  DU23: "1cun directly above midpoint of anterior hairline",
  DU24: "0.5cun directly above midpoint of anterior hairline",
  DU25: "On the tip of the nose",
  DU26: "At the junction of the upper lip and philtrum",
  DU27: "On the median tBLercle of the upper lip",
  DU28: "At the junction of the gum and frenulum of the upper lip",
  LU1: "Laterosuperior to sternum at the lateral side of the 1st intercostal space, 6 cun lateral to the Ren Meridian",
  LU2: "In the depression below acromial extremity of the clavicle, 6 cun lateral to the Ren Meridian",
  LU3: "On the medial aspect of upper arm, 3 cun below the end of axillary fold, on radial side of biceps brachii",
  LU4: "On the medial aspect of upper arm, 4 cun below LU3, on radial side of biceps brachii",
  LU5: "On the cBLital crease, radial side of tendon of biceps brachii",
  LU6: "On palmar aspect of forearm, on line joining LU9 and LU5, 7 cun above wrist crease",
  LU7: "Superior to styloid process of radius, 1.5 cun above wrist crease",
  LU8: "1 cun above wrist crease, in depression on lateral side of radial artery",
  LU9: "At radial end of transverse crease of wrist, in depression on lateral side of radial artery",
  LU10: "On radial aspect of midpoint of 1st metacarpal bone, at junction of red and white skin",
  LU11: "On radial side of thumb, about 0.1 cun posterior to corner of nail",

  LI1: "On radial side of index finger, about 0.1 cun posterior to corner of nail",
  LI2: "On radial side of index finger, distal to metacarpophalangeal joint, at junction of red and white skin",
  LI3: "On radial side of index finger, proximal to head of 2nd metacarpal bone",
  LI4: "On dorsum of hand, between 1st and 2nd metacarpal bones, at midpoint of 2nd metacarpal bone on radial side",
  LI5: "When thumb is tilted upward, in depression between tendons of extensor pollicis longus and brevis",
  LI6: "3 cun above LI5 on line joining LI5 and LI11",
  LI7: "5 cun above LI5 on line joining LI5 and LI11",
  LI8: "4 cun below LI11 on line joining LI5 and LI11",
  LI9: "3 cun below LI11 on line joining LI5 and LI11",
  LI10: "2 cun below LI11 on line joining LI5 and LI11",
  LI11: "At lateral end of transverse cBLital crease, midway between LU5 and lateral epicondyle of humerus",
  LI12: "Superior to lateral epicondyle of humerus, about 1 cun superolateral to LI11",
  LI13: "On line joining LI11 and LI15, 3 cun above LI11",
  LI14: "On line joining LI11 and LI15, 7 cun above LI11, at insertion of deltoid muscle",
  LI15: "Anterior and inferior to acromion, between deltoid and pectoralis major",
  LI16: "In depression between acromial extremity of clavicle and scapular spine",
  LI17: "On lateral side of neck, 1 cun below LI18 on posterior border of sternocleidomastoid muscle",
  LI18: "On lateral side of neck, level with tip of Adam’s apple, between sternal and clavicular heads of SCM",
  LI19: "Right below lateral margin of nostril, 0.5 cun lateral to DU26",
  LI20: "In nasolabial groove, at level of midpoint of lateral border of ala nasi",
  ST1: "With the eyes looking straight forward, directly below the pupil, between the eyeball and infraorbital ridge",
  ST2: "Directly below ST1, in the depression at the infraorbital foramen",
  ST3: "Directly below ST2, level with the lower border of the ala nasi, lateral to the nasolabial groove",
  ST4: "Lateral to the corner of the mouth, directly below ST3",
  ST5: "On the anterior border of the attached portion of the masseter, in the groove appearing when the cheek is bulged",
  ST6: "One finger-breadth anterior and superior to the lower angle of the mandible where the masseter attaches",
  ST7: "At the lower border of the zygomatic arch, in the depression anterior to the condyloid process of the mandible",
  ST8: "0.5 cun within the anterior hairline at the corner of the forehead, 4.5 cun lateral to DU24",
  ST9: "Level with the tip of Adam’s apple, just lateral to the common carotid artery, on the anterior border of the SCM",
  ST10: "Midpoint of the line joining ST9 and ST11, on the anterior border of the SCM",
  ST11: "Superior border of the sternal extremity of the clavicle, between sternal and clavicular heads of the SCM",
  ST12: "In the midpoint of the supraclavicular fossa, 4 cun lateral to the Ren meridian",
  ST13: "At the lower border of the middle of the clavicle, 4 cun lateral to the Ren meridian",
  ST14: "In the 1st intercostal space, 4 cun lateral to the Ren meridian",
  ST15: "In the 2nd intercostal space, 4 cun lateral to the Ren meridian",
  ST16: "In the 3rd intercostal space, 4 cun lateral to the Ren meridian",
  ST17: "In the 4th intercostal space, 4 cun lateral to the Ren meridian (reference only, not needled)",
  ST18: "In the 5th intercostal space, 4 cun lateral to the Ren meridian, directly below the nipple",
  ST19: "6 cun above the umbilicus, 2 cun lateral to RN14",
  ST20: "5 cun above the umbilicus, 2 cun lateral to RN13",
  ST21: "4 cun above the umbilicus, 2 cun lateral to RN12",
  ST22: "3 cun above the umbilicus, 2 cun lateral to RN11",
  ST23: "2 cun above the umbilicus, 2 cun lateral to RN10",
  ST24: "1 cun above the umbilicus, 2 cun lateral to RN9",
  ST25: "2 cun lateral to the center of the umbilicus",
  ST26: "1 cun below the umbilicus, 2 cun lateral to RN7",
  ST27: "2 cun below the umbilicus, 2 cun lateral to RN5",
  ST28: "3 cun below the umbilicus, 2 cun lateral to RN4",
  ST29: "4 cun below the umbilicus, 2 cun lateral to RN3",
  ST30: "5 cun below the umbilicus, 2 cun lateral to RN2, in the groin region",
  ST31: "At the lower border of the symphysis pBLis, in the depression on the lateral side of the sartorius when thigh is flexed",
  ST32: "6 cun above the laterosuperior border of the patella, on the line from ASIS to lateral border of the patella",
  ST33: "3 cun above the laterosuperior border of the patella",
  ST34: "2 cun above the laterosuperior border of the patella, on the line joining ASIS and lateral border of patella",
  ST35: "Below the patella, lateral to the patellar ligament, when knee is flexed",
  ST36: "3 cun below ST35, one finger-breadth from the anterior crest of tibia, in tibialis anterior",
  ST37: "3 cun below ST36, one finger-breadth from the anterior crest of tibia, in tibialis anterior",
  ST38: "8 cun below ST36, one finger-breadth from the anterior crest of tibia",
  ST39: "3 cun below ST37, one finger-breadth from the anterior crest of tibia",
  ST40: "8 cun superior to the external malleolus, one finger-breadth lateral to ST38",
  ST41: "On the ankle crease, between tendons of extensor digitorum longus and hallucis longus",
  ST42: "Highest point of dorsum of foot, between 2nd and 3rd metatarsal bones and cuneiform bone",
  ST43: "In the depression distal to junction of 2nd and 3rd metatarsal bones",
  ST44: "Proximal to web margin between 2nd and 3rd toes, distal and lateral to 2nd metatarsophalangeal joint",
  ST45: "On the lateral side of 2nd toe, 0.1 cun posterior to corner of nail",

  SP1: "On medial side of great toe, 0.1 cun posterior to corner of nail",
  SP2: "On medial side of great toe, distal and inferior to 1st metatarsophalangeal joint, at junction of red and white skin",
  SP3: "Proximal and inferior to head of 1st metatarsal bone, at junction of red and white skin",
  SP4: "In depression distal and inferior to base of 1st metatarsal bone, at junction of red and white skin",
  SP5: "In depression anterior and inferior to medial malleolus, at lower border of medial malleolus",
  SP6: "3 cun directly above tip of medial malleolus, on posterior border of medial aspect of tibia",
  SP7: "3 cun above SP6 on line joining medial malleolus and SP9",
  SP8: "3 cun below SP9, on line connecting SP9 and medial malleolus",
  SP9: "On lower border of medial condyle of tibia, in depression on medial aspect of tibia",
  SP10: "2 cun above mediosuperior border of patella, on bulge of medial portion of quadriceps femoris",
  SP11: "6 cun above SP10 on line drawn from SP10 to SP12",
  SP12: "On lateral side of femoral artery, at upper border of symphysis pBLis, 3.5 cun lateral to RN2",
  SP13: "0.7 cun superior and 0.5 cun lateral to SP12",
  SP14: "1.3 cun below SP15, 4 cun lateral to Ren, on lateral side of rectus abdominis",
  SP15: "4 cun lateral to center of umbilicus, lateral to rectus abdominis",
  SP16: "3 cun above SP15, 4 cun lateral to RN11",
  SP17: "In 5th intercostal space, 6 cun lateral to Ren",
  SP18: "In 4th intercostal space, 6 cun lateral to Ren",
  SP19: "In 3rd intercostal space, 6 cun lateral to Ren",
  SP20: "In 2nd intercostal space, 6 cun lateral to Ren",
  SP21: "On mid-axillary line, 6 cun below axilla, midway between axilla and free end of 11th rib",

  HT1: "When the upper arm is abducted, the point is in the center of the axilla, on the medial side of the axillary artery",
  HT2: "3 cun above the medial end of the transverse cBLital crease (HT3), in the groove medial to the biceps brachii",
  HT3: "At the medial end of the transverse cBLital crease, in the depression between the medial epicondyle of the humerus and the tendon of the biceps brachii",
  HT4: "On the radial side of the tendon of flexor carpi ulnaris, 1.5 cun above the transverse crease of the wrist",
  HT5: "On the radial side of the tendon of flexor carpi ulnaris, 1 cun above the transverse crease of the wrist",
  HT6: "On the radial side of the tendon of flexor carpi ulnaris, 0.5 cun above the transverse crease of the wrist",
  HT7: "At the ulnar end of the transverse crease of the wrist, in the depression on the radial side of the tendon of flexor carpi ulnaris",
  HT8: "On the palm, between the 4th and 5th metacarpal bones, where the tip of the little finger rests when a fist is made",
  HT9: "On the radial side of the little finger, about 0.1 cun posterior to the corner of the nail",

  SI1: "On the ulnar side of the little finger, about 0.1 cun posterior to the corner of the nail",
  SI2: "On the ulnar side of the little finger, distal to the 5th metacarpophalangeal joint, at the junction of the red and white skin",
  SI3: "On the ulnar side of the hand, proximal to the 5th metacarpophalangeal joint, at the end of the transverse crease",
  SI4: "On the ulnar side of the palm, in the depression between the base of the 5th metacarpal bone and the triquetral bone",
  SI5: "On the dorsal aspect of the wrist, in the depression between the styloid process of the ulna and the triquetral bone",
  SI6: "When the palm faces the chest, in the bony cleft on the radial side of the styloid process of the ulna",
  SI7: "On the line joining SI5 and SI8, 5 cun above SI5",
  SI8: "In the depression between the olecranon of the ulna and the medial epicondyle of the humerus",
  SI9: "When the arm is abducted, 1 cun above the posterior end of the axillary fold",
  SI10: "When the arm is abducted, directly above SI9, in the depression inferior to the scapular spine",
  SI11: "At the junction of the upper and middle thirds of the line connecting the lower border of the scapular spine and the inferior angle of the scapula",
  SI12: "In the center of the suprascapular fossa, directly above SI11",
  SI13: "At the medial extremity of the suprascapular fossa, midway between SI10 and the spinous process of T2",
  SI14: "3 cun lateral to the lower border of the spinous process of T1",
  SI15: "2 cun lateral to the lower border of the spinous process of C7",
  SI16: "On the lateral aspect of the neck, posterior border of the sternocleidomastoid muscle, posterior and superior to LI18",
  SI17: "Posterior to the angle of the mandible, in the depression on the anterior border of the sternocleidomastoid muscle",
  SI18: "Directly below the outer canthus, in the depression at the lower border of the zygoma",
  SI19: "Anterior to the tragus and posterior to the condyloid process of the mandible, in the depression formed when the mouth opens",

  BL1: "0.1 cun superior to the inner canthus of the eye",
  BL2: "On the medial extremity of the eyebrow, in the supraorbital notch",
  BL3: "Directly above BL2, 0.5 cun within the anterior hairline, between DU24 and BL4",
  BL4: "0.5 cun within the anterior hairline, 1.5 cun lateral to DU24",
  BL5: "1 cun directly above the anterior hairline and 1.5 cun lateral to DU23",
  BL6: "1.5 cun lateral to DU22, level with the vertex of the head",
  BL7: "1.5 cun lateral to DU20, level with the upper border of the external occipital protBLerance",
  BL8: "1.5 cun lateral to DU19, level with the upper border of the external occipital protBLerance",
  BL9: "1.3 cun lateral to DU17, on the lateral side of the superior nuchal line",
  BL10: "1.3 cun lateral to the midpoint of the posterior hairline, in the depression on the lateral aspect of trapezius",
  BL11: "1.5 cun lateral to DU13, at the level of the lower border of the spinous process of T1",
  BL12: "1.5 cun lateral to DU12, level with the lower border of the spinous process of T2",
  BL13: "1.5 cun lateral to DU11, level with the lower border of the spinous process of T3",
  BL14: "1.5 cun lateral to DU10, level with the lower border of the spinous process of T4",
  BL15: "1.5 cun lateral to DU9, level with the lower border of the spinous process of T5",
  BL16: "1.5 cun lateral to DU8, level with the lower border of the spinous process of T6",
  BL17: "1.5 cun lateral to DU9 (7th thoracic vertebra)",
  BL18: "1.5 cun lateral to DU8 (9th thoracic vertebra)",
  BL19: "1.5 cun lateral to DU7 (10th thoracic vertebra)",
  BL20: "1.5 cun lateral to DU6 (11th thoracic vertebra)",
  BL21: "1.5 cun lateral to DU5 (12th thoracic vertebra)",
  BL22: "1.5 cun lateral to DU4 (1st lumbar vertebra)",
  BL23: "1.5 cun lateral to DU3 (2nd lumbar vertebra)",
  BL24: "1.5 cun lateral to DU3 (3rd lumbar vertebra)",
  BL25: "1.5 cun lateral to DU3 (4th lumbar vertebra)",
  BL26: "1.5 cun lateral to DU3 (5th lumbar vertebra)",
  BL27: "1.5 cun lateral to DU2 (1st sacral foramen)",
  BL28: "1.5 cun lateral to DU2 (2nd sacral foramen)",
  BL29: "1.5 cun lateral to DU2 (3rd sacral foramen)",
  BL30: "1.5 cun lateral to DU2 (4th sacral foramen)",
  BL31: "In the 1st posterior sacral foramen",
  BL32: "In the 2nd posterior sacral foramen",
  BL33: "In the 3rd posterior sacral foramen",
  BL34: "In the 4th posterior sacral foramen",
  BL35: "0.5 cun lateral to the tip of the coccyx",
  BL36: "At the midpoint of the transverse gluteal fold",
  BL37: "6 cun below BL36 on the line joining BL36 and BL40",
  BL38: "1 cun above BL39 on the medial side of the tendon of biceps femoris",
  BL39: "Lateral to BL40, on the medial border of the tendon of biceps femoris",
  BL40: "Midpoint of popliteal crease, between tendons of biceps femoris and semitendinosus",
  BL41: "3 cun lateral to DU12 (2nd thoracic vertebra)",
  BL42: "3 cun lateral to DU11 (3rd thoracic vertebra)",
  BL43: "3 cun lateral to DU10 (4th thoracic vertebra)",
  BL44: "3 cun lateral to DU9 (5th thoracic vertebra)",
  BL45: "3 cun lateral to DU8 (6th thoracic vertebra)",
  BL46: "3 cun lateral to DU7 (7th thoracic vertebra)",
  BL47: "3 cun lateral to DU7 (9th thoracic vertebra)",
  BL48: "3 cun lateral to DU8 (10th thoracic vertebra)",
  BL49: "3 cun lateral to DU9 (11th thoracic vertebra)",
  BL50: "3 cun lateral to DU8 (12th thoracic vertebra)",
  BL51: "3 cun lateral to DU5 (1st lumbar vertebra)",
  BL52: "3 cun lateral to DU4 (2nd lumbar vertebra)",
  BL53: "3 cun lateral to the 2nd posterior sacral foramen",
  BL54: "3 cun lateral to the 4th posterior sacral foramen",
  BL55: "2 cun below BL40, on line joining BL40 and BL57",
  BL56: "Midway between BL55 and BL57, in the center of the gastrocnemius",
  BL57: "On the posterior leg, between BL40 and BL60, about 8 cun below BL40",
  BL58: "7 cun directly above BL60, posterior border of fibula",
  BL59: "3 cun directly above BL60",
  BL60: "In the depression between external malleolus and Achilles tendon",
  BL61: "Posterior and inferior to external malleolus, below BL60, in depression of calcaneum",
  BL62: "In the depression directly below the external malleolus",
  BL63: "On lateral side of foot, in depression lateral to cBLoid bone",
  BL64: "Below the tBLerosity of the 5th metatarsal bone, at junction of red and white skin",
  BL65: "Posterior to the head of the 5th metatarsal bone, at junction of red and white skin",
  BL66: "In depression anterior to 5th metatarsophalangeal joint",
  BL67: "On the lateral side of small toe, about 0.1 cun posterior to corner of nail",

  KD1: "On the sole, at junction of the anterior one third and posterior two thirds of the sole, between 2nd and 3rd metatarsal bones",
  KD2: "Anterior and inferior to the medial malleolus, in depression on lower border of tBLerosity of navicular bone",
  KD3: "In depression between medial malleolus and Achilles tendon, level with tip of medial malleolus",
  KD4: "Posterior and inferior to medial malleolus, in depression medial to attachment of Achilles tendon",
  KD5: "1 cun directly below KD3, in depression anterior and superior to medial side of calcaneum tBLerosity",
  KD6: "In depression below tip of medial malleolus",
  KD7: "2 cun directly above KD3, on anterior border of Achilles tendon",
  KD8: "0.5 cun anterior to KD7",
  KD9: "5 cun above KD3, at lower end of gastrocnemius, on line from KD3 to KD10",
  KD10: "On medial side of popliteal fossa, between tendons of semitendinosus and semimembranosus",
  KD11: "5 cun below umbilicus, 0.5 cun lateral to RN2",
  KD12: "4 cun below umbilicus, 0.5 cun lateral to RN3",
  KD13: "3 cun below umbilicus, 0.5 cun lateral to RN4",
  KD14: "2 cun below umbilicus, 0.5 cun lateral to RN5",
  KD15: "1 cun below umbilicus, 0.5 cun lateral to RN7",
  KD16: "0.5 cun lateral to the center of umbilicus",
  KD17: "2 cun above umbilicus, 0.5 cun lateral to RN10",
  KD18: "3 cun above umbilicus, 0.5 cun lateral to RN11",
  KD19: "4 cun above umbilicus, 0.5 cun lateral to RN12",
  KD20: "5 cun above umbilicus, 0.5 cun lateral to RN13",
  KD21: "6 cun above umbilicus, 0.5 cun lateral to RN14",
  KD22: "In the 5th intercostal space, 2 cun lateral to the Ren meridian",
  KD23: "In the 4th intercostal space, 2 cun lateral to the Ren meridian",
  KD24: "In the 3rd intercostal space, 2 cun lateral to the Ren meridian",
  KD25: "In the 2nd intercostal space, 2 cun lateral to the Ren meridian",
  KD26: "In the 1st intercostal space, 2 cun lateral to the Ren meridian",
  KD27: "In the depression on the lower border of the clavicle, 2 cun lateral to the Ren meridian",

  PC1: "In the 4th intercostal space, 1 cun lateral to the nipple",
  PC2: "2 cun below the level of the anterior axillary fold, between the two heads of the biceps brachii",
  PC3: "On the transverse cBLital crease, at the ulnar side of the tendon of biceps brachii",
  PC4: "5 cun above the transverse crease of the wrist, between the tendons of palmaris longus and flexor carpi radialis",
  PC5: "3 cun above the transverse crease of the wrist, between the tendons of palmaris longus and flexor carpi radialis",
  PC6: "2 cun above the transverse crease of the wrist, between the tendons of palmaris longus and flexor carpi radialis",
  PC7: "In the middle of the transverse crease of the wrist, between the tendons of palmaris longus and flexor carpi radialis",
  PC8: "Between the 2nd and 3rd metacarpal bones, where the tip of the middle finger touches when a fist is made",
  PC9: "In the center of the tip of the middle finger",

  SJ1: "On the lateral side of the ring finger, about 0.1 cun posterior to the corner of the nail",
  SJ2: "In the depression proximal to the margin of the web between the ring and little fingers",
  SJ3: "On the dorsum of the hand, between the 4th and 5th metacarpal bones, in the depression proximal to the metacarpophalangeal joint",
  SJ4: "On the transverse crease of the dorsum of the wrist, in the depression lateral to the tendon of extensor digitorum communis",
  SJ5: "2 cun above SJ4, between the radius and ulna",
  SJ6: "3 cun above SJ4, between the radius and ulna, on the radial side of the extensor digitorum",
  SJ7: "3 cun above SJ4, between the radius and ulna, on the ulnar side of the extensor digitorum",
  SJ8: "4 cun above SJ4, between the radius and ulna",
  SJ9: "5 cun below the olecranon, on the posterior border of the deltoid muscle",
  SJ10: "When the elbow is flexed, in the depression about 1 cun superior to the olecranon",
  SJ11: "1 cun above SJ10, on the line joining SJ10 and SJ14",
  SJ12: "On the line joining SJ14 and the acromion, on the posterior border of the deltoid muscle",
  SJ13: "On the posterior border of the deltoid muscle, about 1 cun posterior to SJ14",
  SJ14: "In the depression posterior and inferior to the acromion, when the arm is abducted",
  SJ15: "Midway between GB21 and SI13, on the superior angle of the scapula",
  SJ16: "Posterior and inferior to the mastoid process, on the posterior border of the sternocleidomastoid muscle",
  SJ17: "Posterior to the earlobe, in the depression between the mandible and the mastoid process",
  SJ18: "Posterior to the ear, in the depression at the junction of the middle and lower third of the curve formed by SJ17 and SJ20",
  SJ19: "Posterior to the ear, at the junction of the upper and middle third of the curve formed by SJ17 and SJ20",
  SJ20: "Directly above the apex of the ear, within the hairline",
  SJ21: "In the depression anterior to the supratragic notch and slightly superior to the condyloid process of the mandible",
  SJ22: "Anterior and superior to SJ21, on the posterior border of the hairline of the temple where the superficial temporal artery passes",
  SJ23: "In the depression at the lateral end of the eyebrow",
  GB1: "0.5 cun lateral to the outer canthus, in the depression on the lateral side of the orbit",
  GB2: "Anterior to the intertragic notch, at the posterior border of the condyloid process of the mandible",
  GB3: "In front of the ear, on the upper border of the zygomatic arch, directly above ST7",
  GB4: "Within the hairline of the temporal region, at the junction of the upper 1/4 and lower 3/4 of the distance between ST8 and GB7",
  GB5: "Within the hairline of the temporal region, midway of the border line connecting ST8 and GB7",
  GB6: "Within the hairline of the temporal region, at the junction of the lower 1/4 and upper 3/4 of the distance between ST8 and GB7",
  GB7: "Directly above the posterior border of the preauricular hairline, about one finger-breadth anterior to SJ20",
  GB8: "Directly above the apex of the auricle, 1.5 cun above the hairline",
  GB9: "Posterior and superior to the mastoid process, 0.5 cun posterior to GB8",
  GB10: "Posterior and superior to the mastoid process, in the depression about the upper 1/3 of the curve from GB9 to GB12",
  GB11: "Posterior and inferior to the mastoid process, in the depression at the junction of the middle and lower thirds of the curve from GB9 to GB12",
  GB12: "In the depression posterior and inferior to the mastoid process",
  GB13: "0.5 cun within the hairline of the forehead, 3 cun lateral to DU24",
  GB14: "On the forehead, 1 cun directly above the midpoint of the eyebrow",
  GB15: "Directly above GB14, 0.5 cun within the hairline, midway between DU24 and ST8",
  GB16: "1.5 cun above GB15, on the line connecting GB15 and GB20",
  GB17: "1.5 cun posterior to GB16, on the line connecting GB15 and GB20",
  GB18: "1.5 cun posterior to GB17, on the line connecting GB15 and GB20",
  GB19: "1.5 cun posterior to GB18, on the line connecting GB15 and GB20",
  GB20: "In the depression between the origins of the sternocleidomastoid and trapezius muscles, level with DU16",
  GB21: "Midway between DU14 and the acromion, at the highest point of the shoulder",
  GB22: "On the mid-axillary line, 3 cun below the axilla, level with the 4th intercostal space",
  GB23: "1 cun anterior to GB22, at the level of the 4th intercostal space",
  GB24: "In the 7th intercostal space, directly below the nipple",
  GB25: "On the lateral side of the abdomen, on the lower border of the free end of the 12th rib",
  GB26: "Directly below the free end of the 11th rib, at the level of the umbilicus",
  GB27: "In the lateral side of the abdomen, anterior to the anterior superior iliac spine, 3 cun below the level of the umbilicus",
  GB28: "Anterior and inferior to the anterior superior iliac spine, 0.5 cun anterior and inferior to GB27",
  GB29: "In the depression midway between the anterior superior iliac spine and the greater trochanter",
  GB30: "At the junction of the lateral 1/3 and medial 2/3 of the distance between the great trochanter and the hiatus of the sacrum",
  GB31: "On the midline of the lateral aspect of the thigh, 7 cun above the transverse popliteal crease",
  GB32: "On the lateral aspect of thigh, 5 cun above the popliteal crease, between vastus lateralis and biceps femoris",
  GB33: "3 cun above GB34, lateral to the knee joint, between the tendon of biceps femoris and the femur",
  GB34: "In the depression anterior and inferior to the head of the fibula",
  GB35: "7 cun above the tip of the external malleolus, on the posterior border of the fibula",
  GB36: "7 cun above the tip of the external malleolus, on the anterior border of the fibula",
  GB37: "5 cun above the tip of the external malleolus, on the anterior border of the fibula",
  GB38: "4 cun above and slightly anterior to the tip of the external malleolus, on the anterior border of the fibula",
  GB39: "3 cun above the tip of the external malleolus, between the posterior border of the fibula and the tendons of peroneus longus and brevis",
  GB40: "Anterior and inferior to the external malleolus, in the depression on the lateral side of the tendon of extensor digitorum longus",
  GB41: "In the depression distal to the junction of the 4th and 5th metatarsal bones, on the lateral side of the tendon of extensor digiti minimi",
  GB42: "Between the 4th and 5th metatarsal bones, on the medial side of the tendon of extensor digiti minimi",
  GB43: "Between the 4th and 5th toes, proximal to the web margin",
  GB44: "On the lateral side of the 4th toe, about 0.1 cun posterior to the corner of the nail",

  LV1: "On the lateral side of the dorsum of the great toe, about 0.1 cun from the corner of the nail",
  LV2: "On the dorsum of the foot, between the 1st and 2nd toes, proximal to the margin of the web",
  LV3: "On the dorsum of the foot, in the depression distal to the junction of the 1st and 2nd metatarsal bones",
  LV4: "Anterior to the medial malleolus, midway between SP5 and ST41, in the depression on the medial side of the tendon of tibialis anterior",
  LV5: "5 cun above the tip of the medial malleolus, on the medial aspect of the tibia",
  LV6: "7 cun above the tip of the medial malleolus, on the medial aspect of the tibia",
  LV7: "Posterior and inferior to the medial condyle of the femur, in the depression superior to the medial end of the popliteal crease",
  LV8: "When the knee is flexed, in the depression superior to the medial end of the transverse popliteal crease, anterior to the insertion of semimembranosus and semitendinosus",
  LV9: "4 cun above the medial epicondyle of the femur, between vastus medialis and sartorius",
  LV10: "3 cun directly below ST30, on the lateral border of adductor longus",
  LV11: "2 cun directly below ST30, on the lateral border of adductor longus",
  LV12: "Inferior and lateral to the pBLic spine, 2.5 cun lateral to the Ren meridian, in the inguinal groove lateral and inferior to ST30",
  LV13: "On the lateral side of the abdomen, below the free end of the 11th floating rib",
  LV14: "Directly below the nipple, in the 6th intercostal space",
};
