const masterTungPoints11 = [
  {
    code: "11.01",
    pinyin: "Dà Jiān",
    name: "Da Jian",
    chinese: "大間穴",
    translation: "Big Space",
    location: "2nd finger, middle of 1st segment, B line (palmar radial).",
    points: 1,
  },
  {
    code: "11.02",
    pinyin: "Xiǎo Jiān",
    name: "Xiao Jian",
    chinese: "小間穴",
    translation: "Small Space",
    location:
      "2nd finger, 1st segment between Da Jian and distal crest, B line (palmar radial).",
    points: 1,
  },
  {
    code: "11.03",
    pinyin: "Fú Jiān",
    name: "Fu Jian",
    chinese: "浮間穴",
    translation: "Floating Distance",
    location:
      "2nd finger, proximal third of 2nd segment, B line (palmar radial).",
    points: 1,
  },
  {
    code: "11.04",
    pinyin: "Wài Jiān",
    name: "Wai Jian",
    chinese: "外間穴",
    translation: "Outer Distance",
    location:
      "2nd finger, distal third of 2nd segment, B line (palmar radial).",
    points: 1,
  },
  {
    code: "11.05",
    pinyin: "Zhōng Jiān",
    name: "Zhong Jian",
    chinese: "中間穴",
    translation: "Center Distance",
    location: "2nd finger, middle of 1st segment, C line (palmar middle).",
    points: 1,
  },
  {
    code: "11.06",
    pinyin: "Huán Cháo",
    name: "Huan Chao",
    chinese: "還巢穴",
    translation: "Return to Nest",
    location: "4th finger, center of middle segment, E line (ulnar).",
    points: 1,
  },
  {
    code: "11.07",
    pinyin: "Zhǐ Sīmǎ",
    name: "Zhi Sima",
    chinese: "指四馬穴",
    translation: "Finger Four Horses",
    location:
      "2nd finger, middle segment, 3 points on E line (ulnar), divide into four equal parts.",
    points: 3,
  },
  {
    code: "11.08",
    pinyin: "Zhǐ Wǔ Jīn Zhǐ Qiān Jīn",
    name: "Zhi Wu Jin Zhi Qian Jin",
    chinese: "指五金穴 指千金穴",
    translation: "Finger Five Metal and Finger One Thousand Metal",
    location:
      "2nd finger, lower segment, 3 points on F line (dorsal ulnar), divide into four equal parts.",
    points: 3,
  },
  {
    code: "11.09",
    pinyin: "Xīn Xī",
    name: "Xin Xi",
    chinese: "心膝穴",
    translation: "Heart Knee",
    location:
      "Middle finger, middle of 2nd segment, 2 points on F and H lines (dorsal ulnar and dorsal radial).",
    points: 2,
  },
  {
    code: "11.10",
    pinyin: "Mù Huǒ",
    name: "Mu Huo",
    chinese: "木火穴",
    translation: "Wood Fire",
    location:
      "Middle finger, joint between 2nd and 3rd segments, G line (dorsal middle).",
    points: 1,
  },
  {
    code: "11.11",
    pinyin: "Fèi Xīn",
    name: "Fei Xin",
    chinese: "肺心穴",
    translation: "Lung Heart",
    location:
      "Middle finger, middle of 2nd segment, G line (dorsal middle), 3 points divided into four parts.",
    points: 3,
  },
  {
    code: "11.12",
    pinyin: "Èr Jiǎo Míng",
    name: "Er Jiao Ming",
    chinese: "二角明穴",
    translation: "Two Bright Corners",
    location:
      "Middle finger, middle of 1st segment, G line (dorsal middle), 2 points divided into three parts.",
    points: 2,
  },
  {
    code: "11.13",
    pinyin: "Dǎn",
    name: "Dan",
    chinese: "膽穴",
    translation: "Gallbladder",
    location:
      "Middle finger, middle of 1st segment, F and H lines (dorsal ulnar and dorsal radial), 2 points divided equally.",
    points: 2,
  },
  {
    code: "11.14",
    pinyin: "Zhǐ Sān Zhòng",
    name: "Zhi San Zhong",
    chinese: "指三重穴",
    translation: "Finger Three Weights",
    location:
      "Ring finger, middle of 2nd segment, F line (dorsal ulnar), 3 points divided into four parts.",
    points: 3,
  },
  {
    code: "11.15",
    pinyin: "Zhǐ Shèn",
    name: "Zhi Shen",
    chinese: "指腎穴",
    translation: "Kidney Finger",
    location:
      "Ring finger, middle of 1st segment, F line (dorsal ulnar), 3 points divided into four parts.",
    points: 3,
  },
  {
    code: "11.16",
    pinyin: "Huǒ Xī",
    name: "Huo Xi",
    chinese: "火膝穴",
    translation: "Fire Knee",
    location:
      "5th finger, joint between 2nd and 3rd segments, H line (dorsal radial).",
    points: 1,
  },
  {
    code: "11.17",
    pinyin: "Mù",
    name: "Mu",
    chinese: "木穴",
    translation: "Wood",
    location:
      "2nd finger, middle of 1st segment, D line (palmar ulnar), 2–3 points divided into three parts.",
    points: 3,
  },
  {
    code: "11.18",
    pinyin: "Pí Zhǒng",
    name: "Pi Zhong",
    chinese: "脾腫穴",
    translation: "Spleen Swelling",
    location:
      "3rd finger, middle of 2nd segment, C line (palmar middle), 2 points divided into four parts.",
    points: 2,
  },
  {
    code: "11.19",
    pinyin: "Xīn Cháng",
    name: "Xin Chang",
    chinese: "心常穴",
    translation: "Normal Heart",
    location:
      "3rd finger, middle of 1st segment, D line (palmar ulnar), 2–3 points divided into four parts.",
    points: 3,
  },
  {
    code: "11.20",
    pinyin: "Mù Yán",
    name: "Mu Yan",
    chinese: "木炎穴",
    translation: "Wood Inflammation",
    location:
      "4th finger, middle of 2nd segment, D line (palmar ulnar), 3 points divided into four parts.",
    points: 3,
  },
  {
    code: "11.21",
    pinyin: "Sān Yǎn",
    name: "San Yan",
    chinese: "三眼穴",
    translation: "Three Eyes",
    location:
      "4th finger, 1st segment, B line (palmar radial), 3 points divided into four equal parts.",
    points: 3,
  },
  {
    code: "11.22",
    pinyin: "Fù Yuán",
    name: "Fu Yuan",
    chinese: "復原穴",
    translation: "Recovery",
    location:
      "4th finger, 1st segment, D line (palmar ulnar), 3 points divided into four equal parts.",
    points: 3,
  },
  {
    code: "11.23",
    pinyin: "Yǎn Huáng",
    name: "Yan Huang",
    chinese: "眼黃穴",
    translation: "Yellow Eyes",
    location:
      "5th finger, palmar side, C line (palmar middle). Yan Huang Yi: middle of 2nd segment. Yan Huang Er: middle of 1st segment.",
    points: 2,
  },
  {
    code: "11.24",
    pinyin: "Fù Kē",
    name: "Fu Ke",
    chinese: "婦科穴",
    translation: "Gynecology",
    location:
      "Thumb, 1st segment, E line (ulnar), 2 points divided into three parts. Hu Wen Zhi adds: 5 points on dorsal part of 1st finger, 1st segment, E line (ulnar), divided into six parts.",
    points: 2,
  },
  {
    code: "11.25",
    pinyin: "Zhǐ Xián",
    name: "Zhi Xian",
    chinese: "止涎穴",
    translation: "Stop Drooling",
    location:
      "Thumb, 1st segment, A line (radial), 2 points divided into three equal parts.",
    points: 2,
  },
  {
    code: "11.26",
    pinyin: "Zhì Wū",
    name: "Zhi Wu",
    chinese: "制污穴",
    translation: "Control Dirt",
    location:
      "Thumb, dorsal side, middle of proximal segment, G line (dorsal middle), 3 points divided into four equal parts.",
    points: 3,
  },
  {
    code: "11.27",
    pinyin: "Wǔ Hǔ",
    name: "Wu Hu",
    chinese: "五虎穴",
    translation: "Five Tigers",
    location:
      "1st finger, palmar side, 1st segment, A line (radial), 5 points divided into six equal parts.",
    points: 5,
  },
  {
    code: null,
    pinyin: "Bā Guān",
    name: "Ba Guan",
    chinese: "八關穴",
    translation: "Eight Passages",
    location:
      "Fingers 2–5, dorsal side, 1st segment, 8 total points. Each finger (2–5) has 2 points: one on A line (radial) and one on E line (ulnar), each 0.25 cun distal to the metacarpophalangeal joint.",
    points: 8,
  },
  {
    code: null,
    pinyin: "Cè Jiān",
    name: "Ce Jian",
    chinese: "側間穴",
    translation: "Side Distance",
    location:
      "2nd finger, 1st segment, B line (palmar radial), located between 11.01 Da Jian and the distal crest of the 1st segment.",
    points: 1,
  },
  {
    code: null,
    pinyin: "Chén Yīn, Nèi Yīn",
    name: "Chen Yin, Nei Yin",
    chinese: "沉陰穴, 內陰穴",
    translation: "Internal Yin, Heavy Yin",
    location:
      "Nei Yin: 2nd finger, A line (radial), lower third of 3rd segment. Chen Yin: 2nd finger, A line (radial), upper third of 1st segment.",
    needling:
      "Perpendicular 0.2–0.4 cun. Can be needled on both sides for better results.",
    reaction_area: "Liver, Six-Fu. Chen Yin: Heart, Liver-sub-branch, Six-Fu.",
    indications: null,
  },
  {
    code: null,
    pinyin: "Dìng Chuǎn",
    name: "Ding Chuan",
    chinese: "定喘穴",
    translation: "Stop Panting",
    location:
      "4th finger, 2nd segment, palmar side, B line (palmar radial); 3 points dividing the segment into four equal parts.",
    needling: "Perpendicular 0.2–0.3 cun.",
    reaction_area: "Spleen, Lung-branch.",
    indications: [
      "Wheezing, asthma.",
      "Congestive heart failure (heart failure).",
    ],
  },
  {
    code: null,
    pinyin: "Fèi Líng",
    name: "Fei Ling",
    chinese: "肺靈穴",
    translation: "Efficient Lungs",
    location:
      "Fei Ling Yi: 2nd finger, palmar side, crease between 1st and 2nd segments on D line (palmar ulnar). Fei Ling Er: same crease on B line (palmar radial).",
    needling: "Perpendicular 0.2–0.3 cun. For high fever, bleed the points.",
    reaction_area: "Lung.",
    indications: ["Asthma", "Bronchitis", "Pneumonia", "High fever"],
  },
  {
    code: null,
    pinyin: "Fèng Cháo",
    name: "Feng Chao",
    chinese: "鳳巢穴",
    translation: "Phoenix Nest",
    location:
      "4th finger, 1st segment, A line (radial), 3 points dividing the segment into four equal parts.",
    needling:
      "Perpendicular 0.2–0.5 cun. Easier to needle from dorsal side of hand.",
    reaction_area: "Liver-assistant, Kidney-assistant.",
    indications: [
      "Uterine cancer or tumor, metritis (uterus inflammation)",
      "Endometriosis, myoma",
    ],
  },
  {
    code: null,
    pinyin: "Fēn Shuǐ",
    name: "Fen Shui",
    chinese: "分水穴",
    translation: "Separate Water",
    location:
      "5th finger, 1st segment, palmar side, B line (palmar radial); 3 points dividing the segment into four equal parts.",
    needling: "Perpendicular 0.2–0.3 cun.",
    reaction_area: "Kidney.",
    indications: [
      "Nephritis, edema.",
      "Tinnitus, deafness due to kidney diseases.",
      "Sciatica, lumbago (lower back pain), herniated disc – lumbar.",
      "Hallux (big toe) pain.",
    ],
  },
  {
    code: null,
    pinyin: "Huǒ Lóng",
    name: "Huo Long",
    chinese: "火龍穴",
    translation: "Dragon Fire",
    location:
      "3rd finger, 1st segment, palmar side, B line (palmar radial); 3 points dividing the segment into four equal parts.",
    needling: "Perpendicular 0.2–0.3 cun.",
    reaction_area: "Heart.",
    indications: [
      "Cardiomegaly (heart enlarged)",
      "Cardialgia (heart pain)",
      "Chest oppression (chest tightness), pleurodynia (chest pain)",
      "Dorsalgia (back pain)",
    ],
  },
  {
    code: null,
    pinyin: "Huǒ Xīng",
    name: "Huo Xing",
    chinese: "火星穴",
    translation: "Fire Star",
    location:
      "3rd finger, aspect side along C line (palmar middle): Huo Xing Xia in middle of 2nd segment; Huo Xing Shang in middle of 1st segment.",
    needling:
      "Perpendicular 0.2–0.3 cun. Bloodletting. Points can be needled bilaterally.",
    reaction_area: "Heart-branch, Lung-branch.",
    indications: null,
  },
  {
    code: null,
    pinyin: "Jiàn Pí",
    name: "Jian Pi",
    chinese: "建脾穴",
    translation: "Establishing Spleen",
    location:
      "4th finger, 1st segment, dorsal side on H line (dorsal radial); 3 points dividing the segment into four equal parts.",
    needling: "Perpendicular 0.1–0.3 cun.",
    reaction_area: "Spleen.",
    indications: [
      "Facial swelling.",
      "Facial itching.",
      "Acne.",
      "Dyspnea (shortness of breath).",
      "Enlarged spleen (Splenomegaly).",
      "Pancreatitis.",
    ],
  },
  {
    code: null,
    pinyin: "Kāi Pí",
    name: "Kai Pi",
    chinese: "開脾穴",
    translation: "Open Spleen",
    location: "3rd finger, 3rd segment, palmar aspect, middle of segment.",
    needling: "Perpendicular 0.1–0.2 cun.",
    reaction_area: "Spleen.",
    indications: [
      "Anorexia (poor appetite), appetite poor in children, anorexia nervosa",
      "Vomiting",
      "Chest oppression (chest tightness)",
    ],
  },
  {
    code: null,
    pinyin: "Mù Huá",
    name: "Mu Hua",
    chinese: "木華穴",
    translation: "Flourishing Tree",
    location:
      "3rd finger, 2nd segment, palmar side: Mu Hua Yi on A line (radial) center; Mu Hua Er on E line (ulnar) center.",
    needling: "Transverse 0.2–0.3 cun.",
    reaction_area: "Liver, Spleen.",
    indications: [
      "Pain and swelling in stomach and intestines due to liver diseases",
      "Splenomegaly (enlarged spleen)",
      "Calf cramps",
    ],
  },
  {
    code: null,
    pinyin: "Mù Líng",
    name: "Mu Ling",
    chinese: "木靈穴",
    translation: "Efficient Wood",
    location:
      "Mu Ling Yi: 4th finger, palmar side, at the first crease on line B (palmar radial). Mu Ling Er: 4th finger, palmar side, at the first crease on line D (palmar ulnar).",
    needling:
      "Perpendicular 0.2–0.3 cun. Bloodletting or yellow fluid secretion from the joint may occur.",
    reaction_area: "Liver.",
    indications: [
      "Liver cirrhosis, hepatitis, liver cancer (symptom relief), hypochondrium pain.",
      "Cholecystitis (gallbladder inflammation), cholelithiasis (gallstones).",
      "Erectile dysfunction (impotence).",
      "Hemiplegia (one-sided paralysis).",
    ],
  },
  {
    code: null,
    pinyin: "Piān Jiān",
    name: "Pian Jian",
    chinese: "偏肩穴",
    translation: "Dislocated Shoulder",
    location:
      "4th finger, middle of 2nd segment, on line E (ulnar). Same location as Huan Chao (11.06) in Tung’s 1973 text.",
    needling: "Perpendicular 0.2–0.3 cun.",
    reaction_area: "Liver and Spleen.",
    indications: [
      "Upper back and neck pain, neck pain.",
      "Dislocated shoulder, shoulder pain, frozen shoulder.",
    ],
  },
  {
    code: null,
    pinyin: "Qī Huá",
    name: "Qi Hua",
    chinese: "七華穴",
    translation: "Seven Blossoms",
    location:
      "Seven points total: two on each of the 2nd, 3rd, and 4th fingers, and one on the 5th finger. Located on the dorsal side of the fingers, at the joint between the 1st and 2nd segments, on both radial (A) and ulnar (E) lines. The 5th finger has one point on the ulnar (E) line.",
    needling: "Perpendicular 0.1–0.2 cun.",
    reaction_area: "Five Zang.",
    indications: [
      "Headache.",
      "Trigeminal neuralgia.",
      "Tinnitus cerebralis.",
      "Dizziness.",
      "Encephalitis (brain inflammation), brain tumor.",
    ],
  },
  {
    code: null,
    pinyin: "Shuāng Líng",
    name: "Shuang Ling",
    chinese: "雙靈穴",
    translation: "Double Efficiency",
    location:
      "3rd finger, palmar side, at the crease between 1st and 2nd segments. Shuang Ling Yi on line B (palmar radial), Shuang Ling Er on line D (palmar ulnar).",
    needling: "Perpendicular 0.2–0.3 cun.",
    reaction_area: "Heart, Lung-branch, Kidney-branch.",
    indications: [
      "Severe and life-threatening diseases.",
      "Cancer: lung, bone, liver, blood (leukemia), throat, and stomach (symptom relief).",
      "Liver cirrhosis.",
      "Pericarditis (inflammation of the pericardium).",
    ],
  },
  {
    code: null,
    pinyin: "Shuǐ Hǎi",
    name: "Shui Hai",
    chinese: "水海穴",
    translation: "Sea Water",
    location:
      "5th finger, 2nd segment, palmar side, on line D (palmar ulnar). Three points dividing the segment into four equal parts.",
    needling: "Perpendicular 0.2–0.3 cun.",
    reaction_area: "Kidney.",
    indications: [
      "Neck pain, neck sprain.",
      "Dorsalgia (back pain), lumbago (lower back pain).",
      "Sciatica.",
    ],
  },
  {
    code: null,
    pinyin: "Shuǐ Qīng",
    name: "Shui Qing",
    chinese: "水清穴",
    translation: "Clear Water",
    location:
      "5th finger, 2nd segment, palmar side, on line B (palmar radial). Three points dividing the segment into four equal parts.",
    needling: "Perpendicular 0.2–0.3 cun.",
    reaction_area: "Kidney.",
    indications: [
      "Migraine.",
      "Lumbago (lower back pain).",
      "Leg pain.",
      "Orchitis (testicular inflammation).",
      "Nephritis, edema, urinary tract infection (UTI), cystitis (bladder inflammation).",
      "Hallux (big toe) pain.",
    ],
  },
  {
    code: null,
    pinyin: "Shuǐ Yuán",
    name: "Shui Yuan",
    chinese: "水源穴",
    translation: "Water Source",
    location:
      "5th finger, 1st segment, palmar side, on line D (palmar ulnar). Three points dividing the segment into four equal parts.",
    needling: "Perpendicular 0.2–0.3 cun.",
    reaction_area: "Kidney.",
    indications: [
      "Ankylosing spondylitis in the cervical spine.",
      "Hand numbness.",
      "Lower abdomen pain.",
    ],
  },
  {
    code: null,
    pinyin: "Shuǐ Yāo",
    name: "Shui Yao",
    chinese: "水腰穴",
    translation: "Water Waist",
    location:
      "5th finger, 2nd segment, dorsal side. Shui Yao Yi on A line (dorsal radial), Shui Yao Er on G line (dorsal middle), Shui Yao San on E line (dorsal ulnar).",
    needling:
      "Perpendicular 0.1–0.2 cun. Shui Yao Er is needled superficially.",
    reaction_area: "Kidney.",
    indications: ["Migraine.", "Dizziness.", "Lower back pain, sciatica."],
  },
  {
    code: null,
    pinyin: "Shào Bái",
    name: "Shao Bai",
    chinese: "少白穴",
    translation: "Small White",
    location:
      "5th finger, dorsal side, at the joint between the 1st and 2nd segments on the A line (dorsal radial).",
    needling: "Perpendicular 0.1–0.2 cun.",
    reaction_area: "Kidney.",
    indications: [
      "Spine osteophytes (bone spurs).",
      "Lower back pain, sciatica.",
      "Hemorrhoids, fissura ani (anal fissure).",
    ],
  },
  {
    code: null,
    pinyin: "Sān Yáng",
    name: "San Yang",
    chinese: "三陽穴",
    translation: "Three Yang",
    location:
      "2nd finger, 2nd segment, on line A (radial). Three points dividing the segment into four equal parts.",
    needling:
      "Perpendicular 0.2–0.4 cun. Can be needled on both sides for better results.",
    reaction_area: "Liver, Six-Fu.",
    indications: [
      "Inflammation of the testes (orchitis).",
      "Testicular tumor.",
      "Scrotal edema.",
    ],
  },
  {
    code: null,
    pinyin: "Tōng Gǔ",
    name: "Tong Gu",
    chinese: "通骨穴",
    translation: "Connect Bone",
    location:
      "Tong Gu Yi: On the palmar side of the fifth finger, on the first crease on line D (palmar ulnar line). Tong Gu Er: On the palmar side of the fifth finger, on the first crease on line B (palmar radial line).",
    needling: "Perpendicular, 0.2–0.3 cun.",
    reaction_area: "Kidney.",
    indications: [
      "Lumbago (lower back pain).",
      "Sciatica.",
      "Ankylosing spondylitis, lumbar intervertebral disc protrusion.",
    ],
  },
  {
    code: null,
    pinyin: "Tǔ Háng",
    name: "Tu Hang",
    chinese: "土航穴",
    translation: "Navigating Earth",
    location:
      "Tu Hang Yi: On the palmar side of the fourth finger, in the center of the second segment on line C (palmar middle line). Tu Hang Er: On the palmar side of the fourth finger, in the center of the first segment on line C (palmar middle line).",
    needling: "Perpendicular, 0.2–0.3 cun.",
    reaction_area: "Spleen.",
    indications: [
      "Tu Hang Yi: Vomiting, gastritis (stomach lining inflammation) with abdominal pressure and bloating, dizziness, asthma.",
      "Tu Hang Er: Leg numbness, leg pain - lateral.",
    ],
  },
  {
    code: null,
    pinyin: "Tǔ Xìng",
    name: "Tu Xing",
    chinese: "土興穴",
    translation: "Flourishing Earth",
    location:
      "Two points on the palmar side of the third finger, on the first segment along line C (palmar middle line). Tu Xing Yi is at the junction of the first and second quarters; Tu Xing Er is at the junction of the third and fourth quarters.",
    needling: "Perpendicular, 0.2–0.3 cun. Bloodletting.",
    reaction_area: "Spleen, stomach.",
    indications: [
      "Gastritis (stomach lining inflammation), enteritis (intestinal inflammation) - acute.",
      "Splenomegaly (enlarged spleen), splenitis (spleen inflammation).",
      "Hypochondrium pain.",
      "Toothache, gingivitis (gum inflammation).",
    ],
  },
  {
    code: null,
    pinyin: "Xià Jiān",
    name: "Xia Jian",
    chinese: "下間穴",
    translation: "Lower Distance",
    location:
      "On the palmar aspect of the second finger, in the middle of the second segment, on line C (palmar middle line).",
    needling: "Perpendicular, 0.1–0.3 cun.",
    reaction_area: "Heart-sub-branch, Lung-sub-branch, Six-Fu.",
    indications: [
      "Palpitations, chest oppression (chest tightness), knee pain, tremors, blurred vision, inguinal hernia.",
      "Eye itching.",
      "Dizziness.",
      "Dorsalgia (back pain).",
    ],
  },
  {
    code: null,
    pinyin: "Zhèng Shuǐ",
    name: "Zheng Shui",
    chinese: "正水穴",
    translation: "Correct Water",
    location:
      "Three points on the dorsal part of the fifth finger, in the middle of the first segment: Zheng Shui Yi on line H (dorsal radial line), Zheng Shui Er on line G (dorsal middle line), Zheng Shui San on line F (dorsal ulnar line).",
    needling:
      "Perpendicular, 0.1–0.2 cun. Zheng Shui Er is needled superficially.",
    reaction_area: "Kidney.",
    indications: [
      "Lower back pain, back pain.",
      "Lower limbs pain.",
      "Cystitis (urinary bladder inflammation), urinary tract infection (UTI), urethritis.",
    ],
  },
  {
    code: null,
    pinyin: "Zhèng Tǔ",
    name: "Zheng Tu",
    chinese: "正土穴",
    translation: "Correct Earth",
    location:
      "Three points on the dorsal aspect of the middle segment of the fourth finger, along line H (dorsal radial line). Divide the segment into four equal parts.",
    needling: "Perpendicular, 0.2–0.3 cun.",
    reaction_area: "Spleen.",
    indications: [
      "Abdominal pain.",
      "Rectal cancer.",
      "Gastritis (stomach lining inflammation), duodenitis.",
      "Nausea, vomiting.",
      "Pancreatitis.",
      "Skin allergies.",
      "Asthma.",
    ],
  },
  {
    code: null,
    pinyin: "Zhū Yuán",
    name: "Zhu Yuan",
    chinese: "珠圓穴",
    translation: "Round Bead",
    location:
      "Two points on the thumb (first finger), between the first and second segments, on both sides of the crease: one on line A (radial line) and one on line E (ulnar line), close to the bone.",
    needling: "Perpendicular, 0.2–0.5 cun.",
    reaction_area: "Lung, Kidney.",
    indications: [
      "Glaucoma.",
      "Cataract.",
      "Keratitis.",
      "Amblyopia (lazy eye).",
      "Herpes zoster eye.",
      "Retinal degeneration, macular degeneration, retinitis.",
    ],
  },
  {
    code: null,
    pinyin: "Zhǐ Fèi",
    name: "Zhi Fei",
    chinese: "指肺穴",
    translation: "Lung Finger",
    location:
      "Three points located on the radial line on the dorsal aspect of the first segment of the second finger, on line H (dorsal radial line). Divide the segment into four equal parts.",
    needling: "Perpendicular, 0.1–0.2 cun.",
    reaction_area: "Lung sub-branch.",
    indications: [
      "Pharyngitis (throat inflammation).",
      "Bronchitis.",
      "Lower back pain, sciatica.",
      "Calf Pain.",
      "Skin diseases.",
      "Otitis externa (ear infection—external ear).",
    ],
  },
  {
    code: null,
    pinyin: "Zhǐ Sān Huáng",
    name: "Zhi San Huang",
    chinese: "指三黃穴",
    translation: "Finger Three Yellows",
    location:
      "Three points on the palmar part of the thumb, in the first segment along line D (palmar ulnar line). Divide the segment into four equal parts.",
    needling: "Perpendicular, 0.2–0.4 cun.",
    reaction_area: "Liver.",
    indications: [
      "Hepatitis, liver cirrhosis, liver cancer (symptom relief).",
      "Hypochondrium pain.",
      "Dysmenorrhea (menstrual pain), oophoritis (ovarian inflammation), metritis (uterine inflammation).",
      "Lower abdomen pain.",
      "Fatigue due to liver deficiency.",
      "Dizziness.",
    ],
  },
  {
    code: null,
    pinyin: "Zhǐ Wèi",
    name: "Zhi Wei",
    chinese: "指胃穴",
    translation: "Stomach Finger",
    location:
      "Three points on the radial line on the dorsal aspect of the second segment of the second finger, on line H (dorsal radial line). Divide the segment into four equal parts.",
    needling: "Perpendicular, 0.1–0.2 cun.",
    reaction_area: "Lung sub-branch, Six-Fu.",
    indications: [
      "Gastritis (stomach lining inflammation), gastric ulcers (stomach ulcer).",
      "Lung deficiency, cough (due to heat in the lungs).",
      "Skin diseases.",
    ],
  },
  {
    code: null,
    pinyin: "Shī Zhěn",
    name: "Shi Zhen",
    chinese: "失枕穴",
    translation: "Lost Pillow",
    location:
      "On the palmar side of the second segment of the fifth finger, 0.2 cun ulnar and distal to 11.23 Yan Huang, between lines C (palmar middle line) and D (palmar ulnar line).",
    needling: "Perpendicular, 0.2–0.3 cun.",
    reaction_area: "Kidney, Brain.",
    indications: [
      "Neck sprain, torticollis (wry neck).",
      "A feeling of congestion in the head.",
      "Dizziness due to excessive mental work.",
      "Dysequilibrium (impaired sense of balance), balance disorder, vestibular dysfunction.",
    ],
  },
  {
    code: null,
    pinyin: "Sān Xiān",
    name: "San Xian",
    chinese: "三仙穴",
    translation: "Three Immortals",
    location:
      "Three points on the dorsal aspect of the first segment of the second finger, on line G (dorsal middle line). Divide the segment into four equal parts.",
    needling: "Transverse, threading of the three points with one needle.",
    reaction_area: "Lung-branch.",
    indications: [
      "Skin sensitivity.",
      "Skin diseases, scabies, eczema.",
      "Skin swelling due to injury.",
      "Otitis externa (ear infection—external ear).",
    ],
  },
  {
    code: null,
    pinyin: "Xī Líng",
    name: "Xi Ling",
    chinese: "膝靈穴",
    translation: "Effective Knee",
    location:
      "On the dorsal part of the third finger, on both sides of the nail (lateral and medial), 0.2 cun posterior to the nail’s corner. Corresponds to lines F (dorsal ulnar line) and H (dorsal radial line).",
    needling: "Oblique, towards the wrist joint, 0.2 cun.",
    reaction_area: "Heart-assists, Liver, Kidney.",
    indications: [
      "Knee pain.",
      "Rheumatic heart disease.",
      "Toe neuralgia.",
      "Knee osteoarthritis.",
    ],
  },
];
